# Generated by Django 5.2.6 on 2025-09-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compteuser',
            name='fonction',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('support', 'Support Client'), ('developpeur', 'Développeur'), ('marketing', 'Marketing'), ('administrateur', 'Administrateur'), ('comptable', 'Comptable'), ('ressources humaines', 'Ressources humaines')], default='', max_length=200, verbose_name="Fonction dans l'entreprise"),
        ),
        migrations.AlterField(
            model_name='compteuser',
            name='nom',
            field=models.CharField(default='', max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='compteuser',
            name='photo',
            field=models.ImageField(null=True, upload_to='admin_photos/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='compteuser',
            name='prenom',
            field=models.CharField(default='', max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='compteuser',
            name='telephone',
            field=models.CharField(default='', max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='compteuser',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name="Nom d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='type_etablissement',
            field=models.CharField(choices=[('primary', 'École Primaire'), ('collège', 'Collège'), ('lycée', 'Lycée')], max_length=20, verbose_name="Type d'établissement"),
        ),
    ]
