# Generated by Django 5.2.6 on 2025-09-26 23:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0002_etablissement_last_login_etablissement_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etablissement', models.CharField(max_length=255, verbose_name='Nom de la prospection')),
                ('type_etablissement', models.CharField(max_length=255, verbose_name='Type de la prospection')),
                ('statut_etablissement', models.CharField(max_length=255, verbose_name='Statut de la prospection')),
                ('ville_etablissement', models.CharField(max_length=255, verbose_name='Ville de la prospection')),
                ('pays_etablissement', models.CharField(max_length=255, verbose_name='Pays de la prospection')),
                ('adresse_etablissement', models.TextField(verbose_name='Adresse de la prospection')),
                ('potentiel_etablissement', models.CharField(max_length=255, verbose_name='Potentiel de la prospection')),
                ('priorite_etablissement', models.CharField(max_length=255, verbose_name='Priorité de la prospection')),
                ('source_etablissement', models.CharField(max_length=255, verbose_name='Source de la prospection')),
                ('prochaine_action_etablissement', models.CharField(max_length=255, verbose_name='Prochaine action de la prospection')),
                ('notes_commercial', models.TextField(verbose_name='Notes de la prospection')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Prospection',
                'verbose_name_plural': 'Prospections',
                'ordering': ['-date_creation'],
            },
        ),
    ]
