# Generated by Django 5.2.6 on 2025-09-26 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0003_prospection'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospection',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
    ]
