# Generated by Django 5.2.6 on 2025-09-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0004_prospection_cree_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospection',
            name='notes_commercial',
            field=models.TextField(blank=True, null=True, verbose_name='Notes de la prospection'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='prochaine_action_etablissement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Prochaine action de la prospection'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='source_etablissement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source de la prospection'),
        ),
    ]
