# Generated by Django 5.2.6 on 2025-09-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0005_alter_prospection_notes_commercial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospection',
            name='adresse_etablissement',
            field=models.TextField(verbose_name='Adresse complète'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='nom_etablissement',
            field=models.CharField(max_length=255, verbose_name="Nom de l'établissement"),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='notes_commercial',
            field=models.TextField(blank=True, null=True, verbose_name='Notes commerciales'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='pays_etablissement',
            field=models.CharField(choices=[('senegal', 'Sénégal'), ('cote_ivoire', "Côte d'Ivoire"), ('mali', 'Mali'), ('burkina_faso', 'Burkina Faso'), ('niger', 'Niger'), ('guinee', 'Guinée'), ('autre', 'Autre')], max_length=255, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='potentiel_etablissement',
            field=models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé'), ('tres_eleve', 'Très élevé')], max_length=255, verbose_name='Potentiel commercial'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='priorite_etablissement',
            field=models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], max_length=255, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='prochaine_action_etablissement',
            field=models.CharField(blank=True, choices=[('recherche_contact', 'Rechercher les contacts'), ('appel_telephonique', 'Appel téléphonique'), ('email', "Envoi d'email"), ('visite', 'Visite sur site'), ('presentation', 'Présentation')], max_length=255, null=True, verbose_name='Prochaine action'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='source_etablissement',
            field=models.CharField(blank=True, choices=[('recommandation', 'Recommandation'), ('site_web', 'Site web'), ('reseau_social', 'Réseau social'), ('salon', 'Salon/Événement'), ('appel_froid', 'Appel froid'), ('autre', 'Autre')], max_length=255, null=True, verbose_name='Source de prospection'),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='statut_etablissement',
            field=models.CharField(choices=[('public', 'Public'), ('prive', 'Privé'), ('confessionnel', 'Confessionnel')], max_length=255, verbose_name="Statut d'établissement"),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='type_etablissement',
            field=models.CharField(choices=[('primaire', 'École primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université'), ('autre', 'Autre')], max_length=255, verbose_name="Type d'établissement"),
        ),
        migrations.AlterField(
            model_name='prospection',
            name='ville_etablissement',
            field=models.CharField(max_length=255, verbose_name='Ville'),
        ),
    ]
