# Generated by Django 5.2.6 on 2025-09-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0006_alter_prospection_adresse_etablissement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospection',
            name='notes_rendezvous',
            field=models.TextField(blank=True, null=True, verbose_name='Notes de rendez-vous'),
        ),
    ]
