# Generated by Django 5.2.6 on 2025-09-27 15:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0007_prospection_notes_rendezvous'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu de la note')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_commerciales', to='school_admin.prospection', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Note commerciale',
                'verbose_name_plural': 'Notes commerciales',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rdv', models.CharField(choices=[('appel_telephonique', 'Appel téléphonique'), ('visite_site', 'Visite sur site'), ('presentation_online', 'Présentation en ligne'), ('dejeuner_affaires', "Déjeuner d'affaires"), ('salon_rencontre', 'Salon/Rencontre'), ('autre', 'Autre')], max_length=50, verbose_name='Type de rendez-vous')),
                ('date_rdv', models.DateField(verbose_name='Date du rendez-vous')),
                ('heure_rdv', models.TimeField(verbose_name='Heure du rendez-vous')),
                ('notes_rdv', models.TextField(blank=True, null=True, verbose_name='Notes sur le rendez-vous')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='school_admin.prospection', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-date_creation'],
            },
        ),
    ]
