# Generated by Django 5.2.6 on 2025-09-27 16:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0008_notecommercial_rendezvous'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteRendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du compte rendu')),
                ('contenu', models.TextField(verbose_name='Contenu du compte rendu')),
                ('date_visite', models.DateField(verbose_name='Date de la visite')),
                ('duree_visite', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée de la visite (minutes)')),
                ('personnes_rencontrees', models.TextField(blank=True, null=True, verbose_name='Personnes rencontrées')),
                ('points_cles', models.TextField(blank=True, null=True, verbose_name='Points clés discutés')),
                ('prochaines_etapes', models.TextField(blank=True, null=True, verbose_name='Prochaines étapes')),
                ('satisfaction_client', models.CharField(blank=True, choices=[('tres_satisfait', 'Très satisfait'), ('satisfait', 'Satisfait'), ('neutre', 'Neutre'), ('peu_satisfait', 'Peu satisfait'), ('pas_satisfait', 'Pas satisfait')], max_length=20, null=True, verbose_name='Satisfaction du client')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_rendus', to='school_admin.prospection', verbose_name='Établissement')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compte_rendu', to='school_admin.rendezvous', verbose_name='Rendez-vous associé')),
            ],
            options={
                'verbose_name': 'Compte rendu',
                'verbose_name_plural': 'Comptes rendus',
                'ordering': ['-date_creation'],
            },
        ),
    ]
