# Generated by Django 5.2.6 on 2025-09-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0009_compterendu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compterendu',
            name='duree_visite',
        ),
        migrations.RemoveField(
            model_name='compterendu',
            name='personnes_rencontrees',
        ),
        migrations.RemoveField(
            model_name='compterendu',
            name='points_cles',
        ),
        migrations.RemoveField(
            model_name='compterendu',
            name='prochaines_etapes',
        ),
        migrations.AlterField(
            model_name='compterendu',
            name='satisfaction_client',
            field=models.CharField(choices=[('tres_satisfait', 'Très satisfait'), ('satisfait', 'Satisfait'), ('neutre', 'Neutre'), ('peu_satisfait', 'Peu satisfait'), ('pas_satisfait', 'Pas satisfait')], default='', max_length=20, verbose_name='Satisfaction du client'),
            preserve_default=False,
        ),
    ]
