# Generated by Django 5.2.6 on 2025-09-28 15:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0010_remove_compterendu_duree_visite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255, verbose_name='Sujet du message')),
                ('contenu', models.TextField(verbose_name='Contenu du message')),
                ('type_message', models.CharField(choices=[('demande_info', "Demande d'information"), ('proposition', 'Proposition commerciale'), ('suivi', 'Suivi de prospection'), ('rendez_vous', 'Rendez-vous'), ('devis', 'Devis'), ('contrat', 'Contrat'), ('support', 'Support technique'), ('autre', 'Autre')], default='demande_info', max_length=50, verbose_name='Type de message')),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('non_lu', 'Non lu'), ('lu', 'Lu'), ('repondu', 'Répondu'), ('archive', 'Archivé')], default='non_lu', max_length=20, verbose_name='Statut')),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'envoi")),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='school_admin.prospection', verbose_name='Établissement')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Message commercial',
                'verbose_name_plural': 'Messages commerciaux',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='ReponseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu de la réponse')),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'envoi")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
                ('message_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='school_admin.messagecommercial', verbose_name='Message original')),
            ],
            options={
                'verbose_name': 'Réponse de message',
                'verbose_name_plural': 'Réponses de messages',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
