# Generated by Django 5.2.6 on 2025-09-28 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0011_messagecommercial_reponsemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecommercial',
            name='date_prise_en_charge',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de prise en charge'),
        ),
        migrations.AddField(
            model_name='messagecommercial',
            name='expediteur_type',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('etablissement', 'Établissement')], default='admin', max_length=20, verbose_name="Type d'expéditeur"),
        ),
        migrations.AddField(
            model_name='messagecommercial',
            name='pris_en_charge_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_pris_en_charge', to=settings.AUTH_USER_MODEL, verbose_name='Pris en charge par'),
        ),
        migrations.AddField(
            model_name='messagecommercial',
            name='ticket_statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('ferme', 'Fermé')], default='ouvert', max_length=20, verbose_name='Statut du ticket'),
        ),
    ]
