# Generated by Django 5.2.6 on 2025-09-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0012_messagecommercial_date_prise_en_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospection',
            name='statut_etablissement',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('contacte', 'Contacté'), ('rdv_planifie', 'RDV planifié'), ('proposition', 'Proposition'), ('contrat_signe', 'Contrat signé')], max_length=255, verbose_name="Statut d'établissement"),
        ),
    ]
