# Generated by Django 5.2.6 on 2025-09-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0013_alter_prospection_statut_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospection',
            name='genre_etablissement',
            field=models.CharField(choices=[('public', 'Public'), ('prive', 'Privé'), ('confessionnel', 'Confessionnel')], default='', max_length=255, verbose_name="Genre d'établissement"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prospection',
            name='statut_etablissement',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('contacte', 'Contacté'), ('rendez_vous', 'Rendez-vous'), ('contrat_signe', 'Contrat signé'), ('non_interesse', 'Non intéressé'), ('interesse', 'Intéressé'), ('negociation', 'En négociation'), ('devis_envoye', 'Devis envoyé'), ('contrat_signe', 'Contrat signé')], max_length=255, verbose_name="Statut d'établissement"),
        ),
    ]
