# Generated by Django 5.2.6 on 2025-09-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0014_prospection_genre_etablissement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='module_censora',
            field=models.BooleanField(default=False, verbose_name='Censora'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='module_comptabilite',
            field=models.BooleanField(default=False, verbose_name='Comptabilité'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='module_emploi_temps',
            field=models.BooleanField(default=False, verbose_name='Emploi du temps'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='module_gestion_eleves',
            field=models.BooleanField(default=False, verbose_name='Gestion des élèves'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='module_gestion_personnel',
            field=models.BooleanField(default=False, verbose_name='Gestion du personnel'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='module_notes_evaluations',
            field=models.BooleanField(default=False, verbose_name='Notes et évaluations'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='module_transport_scolaire',
            field=models.BooleanField(default=False, verbose_name='Transport scolaire'),
        ),
    ]
