# Generated by Django 5.2.6 on 2025-09-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0015_add_modules_to_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='module_activites',
            field=models.BooleanField(default=False, verbose_name='Activités extra-scolaires'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='module_bibliotheque',
            field=models.BooleanField(default=False, verbose_name='Gestion de la bibliothèque'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='module_cantine',
            field=models.BooleanField(default=False, verbose_name='Gestion de la cantine'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='module_communication',
            field=models.BooleanField(default=False, verbose_name='Communication parents'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='module_formation',
            field=models.BooleanField(default=False, verbose_name='Formation continue'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='module_orientation',
            field=models.BooleanField(default=False, verbose_name='Orientation scolaire'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='module_sante',
            field=models.BooleanField(default=False, verbose_name='Suivi médical'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='module_surveillance',
            field=models.BooleanField(default=False, verbose_name='Surveillance et sécurité'),
        ),
    ]
