# Generated by Django 5.2.6 on 2025-09-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0016_add_premium_modules_to_etablissement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissement',
            name='module_censora',
        ),
        migrations.AddField(
            model_name='etablissement',
            name='module_censure',
            field=models.BooleanField(default=False, verbose_name='Censure et modération'),
        ),
    ]
