# Generated by Django 5.2.6 on 2025-09-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0017_rename_censora_to_censure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissement',
            name='module_censure',
        ),
        migrations.AddField(
            model_name='etablissement',
            name='module_sensores',
            field=models.BooleanField(default=False, verbose_name='Sensores'),
        ),
    ]
