# Generated by Django 5.2.6 on 2025-09-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0018_rename_censure_to_sensores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissement',
            name='module_sensores',
        ),
        migrations.AddField(
            model_name='etablissement',
            name='module_censeurs',
            field=models.BooleanField(default=False, verbose_name='Censeurs'),
        ),
    ]
