# Generated by Django 5.2.6 on 2025-10-02 21:27

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('school_admin', '0019_rename_sensores_to_censeurs'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='etablissement',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='etablissement',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this establishment belongs to.', related_name='etablissement_set', related_query_name='etablissement', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this establishment.', related_name='etablissement_set', related_query_name='etablissement', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name="Nom d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='compteuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='compte_user_set', related_query_name='compte_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='compteuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='compte_user_set', related_query_name='compte_user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
