# Generated by Django 5.2.6 on 2025-10-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0020_alter_etablissement_managers_and_more'),
    ]

    operations = [
    ]
