# Generated by Django 5.2.6 on 2025-10-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('school_admin', '0021_auto_20251002_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='compteuser_set', related_query_name='compteuser', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='compteuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='compteuser_set', related_query_name='compteuser', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
