# Generated by Django 5.2.6 on 2025-10-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0024_add_etablissement_manytomany_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissementuserpermissions',
            name='etablissement',
        ),
        migrations.RemoveField(
            model_name='etablissementuserpermissions',
            name='permission',
        ),
        migrations.DeleteModel(
            name='EtablissementGroups',
        ),
        migrations.DeleteModel(
            name='EtablissementUserPermissions',
        ),
    ]
