# Generated by Django 5.2.6 on 2025-10-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0026_add_personnel_administratif_model_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personneladministratif',
            name='date_embauche',
        ),
        migrations.RemoveField(
            model_name='personneladministratif',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='personneladministratif',
            name='niveau_etablissement',
        ),
        migrations.RemoveField(
            model_name='personneladministratif',
            name='numero_employe',
        ),
        migrations.RemoveField(
            model_name='personneladministratif',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='personneladministratif',
            name='role',
        ),
        migrations.AddField(
            model_name='personneladministratif',
            name='fonction',
            field=models.CharField(choices=[('secretaire', 'Secrétaire / Service de scolarité'), ('surveillant_general', 'Surveillant Général (SG)'), ('censeur', 'Censeur'), ('administrateur', 'Administrateur')], default='', max_length=50, verbose_name='Fonction'),
            preserve_default=False,
        ),
    ]
