# Generated by Django 5.2.6 on 2025-10-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0027_remove_personneladministratif_date_embauche_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personneladministratif',
            name='numero_employe',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="Numéro d'employé"),
        ),
    ]
