# Generated by Django 5.2.6 on 2025-10-03 20:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0028_personneladministratif_numero_employe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la classe')),
                ('niveau', models.CharField(choices=[('maternelle', 'Maternelle'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('superieur', 'Supérieur')], max_length=20, verbose_name='Niveau')),
                ('code_classe', models.CharField(max_length=20, unique=True, verbose_name='Code de la classe')),
                ('capacite_max', models.PositiveIntegerField(default=30, verbose_name='Capacité maximale')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['niveau', 'nom'],
                'unique_together': {('nom', 'etablissement')},
            },
        ),
    ]
