# Generated by Django 5.2.6 on 2025-10-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0030_eleve'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='nom',
            field=models.CharField(default='', help_text="Nom de famille de l'élève", max_length=100, verbose_name='Nom de famille'),
            preserve_default=False,
        ),
    ]
