# Generated by Django 5.2.6 on 2025-10-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0031_eleve_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='documents_fournis',
        ),
        migrations.AddField(
            model_name='eleve',
            name='document_acte_naissance',
            field=models.BooleanField(default=False, help_text='Acte de naissance fourni', verbose_name='Acte de naissance'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='document_assurance_maladie',
            field=models.BooleanField(default=False, help_text="Attestation d'assurance maladie fournie", verbose_name="Attestation d'assurance maladie"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='document_autorisation_parentale',
            field=models.BooleanField(default=False, help_text='Autorisation parentale fournie', verbose_name='Autorisation parentale'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='document_bulletin_precedent',
            field=models.BooleanField(default=False, help_text="Bulletin de l'année précédente fourni", verbose_name="Bulletin de l'année précédente"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='document_carnet_vaccination',
            field=models.BooleanField(default=False, help_text='Carnet de vaccination fourni', verbose_name='Carnet de vaccination'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='document_certificat_medical',
            field=models.BooleanField(default=False, help_text='Certificat médical fourni', verbose_name='Certificat médical'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='document_certificat_scolarite',
            field=models.BooleanField(default=False, help_text='Certificat de scolarité fourni', verbose_name='Certificat de scolarité'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='document_cni',
            field=models.BooleanField(default=False, help_text="Carte nationale d'identité fournie", verbose_name="Carte nationale d'identité"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='document_justificatif_domicile',
            field=models.BooleanField(default=False, help_text='Justificatif de domicile fourni', verbose_name='Justificatif de domicile'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='document_livret_scolaire',
            field=models.BooleanField(default=False, help_text='Livret scolaire fourni', verbose_name='Livret scolaire'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='document_passeport',
            field=models.BooleanField(default=False, help_text='Passeport fourni', verbose_name='Passeport'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='document_photo_identite',
            field=models.BooleanField(default=False, help_text="Photo d'identité fournie", verbose_name="Photo d'identité"),
        ),
    ]
