# Generated by Django 5.2.6 on 2025-10-04 19:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0032_remove_eleve_documents_fournis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='date_derniere_facturation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière facturation'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='montant_total_facturation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant total de facturation'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='nombre_eleves_factures',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'élèves facturés"),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='statut_paiement',
            field=models.CharField(choices=[('en_attente', 'En attente de paiement'), ('paye', 'Payé'), ('en_retard', 'En retard'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut du paiement'),
        ),
        migrations.CreateModel(
            name='Facturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('type_facture', models.CharField(choices=[('inscription_eleve', "Inscription d'élève"), ('renouvellement_annuel', 'Renouvellement annuel'), ('module_supplementaire', 'Module supplémentaire'), ('penalite', 'Pénalité')], max_length=30, verbose_name='Type de facture')),
                ('montant_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant unitaire')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('paye', 'Payé'), ('en_retard', 'En retard'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_echeance', models.DateTimeField(verbose_name="Date d'échéance")),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('description', models.TextField(help_text='Description détaillée de la facture', verbose_name='Description')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes internes')),
                ('mode_paiement', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mode de paiement')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence de paiement')),
                ('eleves_concernes', models.ManyToManyField(blank=True, related_name='facturations', to='school_admin.eleve', verbose_name='Élèves concernés')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturations', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Facturation',
                'verbose_name_plural': 'Facturations',
                'ordering': ['-date_creation'],
            },
        ),
    ]
