# Generated by Django 5.2.6 on 2025-10-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0034_auto_20251004_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='montant_par_eleve',
            field=models.DecimalField(decimal_places=2, default=3000.0, max_digits=10, verbose_name='Montant par élève (FCFA)'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='type_facturation',
            field=models.CharField(choices=[('mensuel', 'Facturation mensuelle'), ('annuel', 'Facturation annuelle')], default='mensuel', max_length=20, verbose_name='Type de facturation'),
        ),
    ]
