# Generated by Django 5.2.6 on 2025-10-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0035_etablissement_montant_par_eleve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de paiement'), ('paye', 'Payé'), ('en_retard', 'En retard'), ('impaye', 'Impayé'), ('contentieux', 'Contentieux'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
    ]
