# Generated by Django 5.2.6 on 2025-10-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0036_alter_facturation_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturation',
            name='notes',
        ),
        migrations.AlterField(
            model_name='facturation',
            name='type_facture',
            field=models.CharField(choices=[('frais_service_mensuel', 'Frais de service mensuel'), ('frais_service_annuel', 'Frais de service annuel'), ('module_supplementaire', 'Module supplémentaire')], max_length=30, verbose_name='Type de facture'),
        ),
    ]
