# Generated by Django 5.2.6 on 2025-10-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0037_remove_facturation_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturation',
            name='modules_supplementaires',
            field=models.JSONField(blank=True, help_text='Liste des modules supplémentaires sélectionnés', null=True, verbose_name='Modules supplémentaires'),
        ),
    ]
