# Generated by Django 5.2.6 on 2025-10-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0038_facturation_modules_supplementaires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturation',
            name='modules_supplementaires',
        ),
        migrations.AddField(
            model_name='facturation',
            name='module_activites',
            field=models.BooleanField(default=False, verbose_name='Activités extra-scolaires'),
        ),
        migrations.AddField(
            model_name='facturation',
            name='module_bibliotheque',
            field=models.BooleanField(default=False, verbose_name='Gestion de la bibliothèque'),
        ),
        migrations.AddField(
            model_name='facturation',
            name='module_cantine',
            field=models.BooleanField(default=False, verbose_name='Gestion de la cantine'),
        ),
        migrations.AddField(
            model_name='facturation',
            name='module_censeurs',
            field=models.BooleanField(default=False, verbose_name='Censeurs'),
        ),
        migrations.AddField(
            model_name='facturation',
            name='module_communication',
            field=models.BooleanField(default=False, verbose_name='Communication parents'),
        ),
        migrations.AddField(
            model_name='facturation',
            name='module_comptabilite',
            field=models.BooleanField(default=False, verbose_name='Comptabilité'),
        ),
        migrations.AddField(
            model_name='facturation',
            name='module_formation',
            field=models.BooleanField(default=False, verbose_name='Formation continue'),
        ),
        migrations.AddField(
            model_name='facturation',
            name='module_orientation',
            field=models.BooleanField(default=False, verbose_name='Orientation scolaire'),
        ),
        migrations.AddField(
            model_name='facturation',
            name='module_sante',
            field=models.BooleanField(default=False, verbose_name='Suivi médical'),
        ),
        migrations.AddField(
            model_name='facturation',
            name='module_surveillance',
            field=models.BooleanField(default=False, verbose_name='Surveillance et sécurité'),
        ),
        migrations.AddField(
            model_name='facturation',
            name='module_transport_scolaire',
            field=models.BooleanField(default=False, verbose_name='Transport scolaire'),
        ),
    ]
