# Generated by Django 5.2.6 on 2025-10-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0039_remove_facturation_modules_supplementaires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturation',
            name='date_echeance_reste',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'échéance du reste à payer"),
        ),
        migrations.AddField(
            model_name='facturation',
            name='reste_a_payer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Reste à payer'),
        ),
    ]
