# Generated by Django 5.2.6 on 2025-10-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0040_facturation_date_echeance_reste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturation',
            name='paiement_partiel',
            field=models.BooleanField(default=False, verbose_name='Paiement partiel'),
        ),
    ]
