# Generated by Django 5.2.6 on 2025-10-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0041_facturation_paiement_partiel'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturation',
            name='statut_envoi',
            field=models.BooleanField(default=False, verbose_name="Statut d'envoi"),
        ),
    ]
