# Generated by Django 5.2.6 on 2025-10-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0042_facturation_statut_envoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturation',
            name='montant_verse',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant versé'),
        ),
    ]
