# Generated by Django 5.2.6 on 2025-10-05 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0043_add_montant_verse_to_facturation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personneladministratif',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription"),
        ),
        migrations.AlterField(
            model_name='personneladministratif',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='personneladministratif',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='personneladministratif',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Super utilisateur'),
        ),
        migrations.AlterField(
            model_name='personneladministratif',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion'),
        ),
        migrations.AlterField(
            model_name='personneladministratif',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Mot de passe'),
        ),
    ]
