# Generated by Django 5.2.6 on 2025-10-05 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0044_alter_personneladministratif_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription"),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Mot de passe'),
        ),
    ]
