# Generated by Django 5.2.6 on 2025-10-05 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0045_alter_eleve_date_joined_alter_eleve_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='mot_de_passe_provisoire',
            field=models.CharField(default='0000', help_text="Mot de passe provisoire pour l'accès parent/tuteur", max_length=128, verbose_name='Mot de passe provisoire'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
