# Generated by Django 5.2.6 on 2025-10-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0046_alter_eleve_date_joined_alter_eleve_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='adresse',
            field=models.TextField(blank=True, help_text="Adresse de résidence de l'élève (optionnel)", null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='mot_de_passe_provisoire',
            field=models.CharField(help_text="Mot de passe provisoire pour l'accès parent/tuteur", max_length=128, verbose_name='Mot de passe provisoire'),
        ),
    ]
