# Generated by Django 5.2.6 on 2025-10-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0047_alter_eleve_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='email_mere',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='email_pere',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='nom_mere',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='nom_pere',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='telephone_mere',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='telephone_pere',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='tuteur_adresse',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='tuteur_email',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='tuteur_lien',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='tuteur_nom',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='tuteur_prenom',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='tuteur_profession',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='tuteur_telephone',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='type_responsable',
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent_adresse',
            field=models.TextField(blank=True, help_text='Adresse complète du parent ou tuteur (optionnel)', null=True, verbose_name='Adresse du parent/tuteur'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent_email',
            field=models.EmailField(blank=True, help_text='Adresse email du parent ou tuteur (optionnel)', max_length=254, null=True, verbose_name='Email du parent/tuteur'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent_lien',
            field=models.CharField(choices=[('pere', 'Père'), ('mere', 'Mère'), ('grand_parent', 'Grand-parent'), ('oncle_tante', 'Oncle/Tante'), ('frere_soeur', 'Frère/Sœur'), ('autre_famille', 'Autre membre de la famille'), ('tuteur_legal', 'Tuteur légal'), ('autre', 'Autre')], default='', help_text="Lien de parenté du parent/tuteur avec l'élève", max_length=20, verbose_name="Lien avec l'élève"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent_nom',
            field=models.CharField(default='', help_text='Nom de famille du parent ou tuteur', max_length=100, verbose_name='Nom du parent/tuteur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent_prenom',
            field=models.CharField(default='', help_text='Prénom du parent ou tuteur', max_length=100, verbose_name='Prénom du parent/tuteur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent_profession',
            field=models.CharField(blank=True, help_text='Profession du parent ou tuteur (optionnel)', max_length=100, null=True, verbose_name='Profession du parent/tuteur'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent_telephone',
            field=models.CharField(default='', help_text='Numéro de téléphone du parent ou tuteur', max_length=20, verbose_name='Téléphone du parent/tuteur'),
            preserve_default=False,
        ),
    ]
