# Generated by Django 5.2.6 on 2025-10-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0048_remove_eleve_email_mere_remove_eleve_email_pere_and_more'),
    ]

    operations = [
        
        # Ajouter les nouveaux champs
        migrations.AddField(
            model_name='eleve',
            name='parent_nom',
            field=models.CharField(max_length=100, verbose_name="Nom du parent/tuteur", help_text="Nom de famille du parent ou tuteur"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent_prenom',
            field=models.CharField(max_length=100, verbose_name="Prénom du parent/tuteur", help_text="Prénom du parent ou tuteur"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent_telephone',
            field=models.CharField(max_length=20, verbose_name="Téléphone du parent/tuteur", help_text="Numéro de téléphone du parent ou tuteur"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent_email',
            field=models.EmailField(blank=True, null=True, verbose_name="Email du parent/tuteur", help_text="Adresse email du parent ou tuteur (optionnel)"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent_adresse',
            field=models.TextField(blank=True, null=True, verbose_name="Adresse du parent/tuteur", help_text="Adresse complète du parent ou tuteur (optionnel)"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent_profession',
            field=models.CharField(max_length=100, blank=True, null=True, verbose_name="Profession du parent/tuteur", help_text="Profession du parent ou tuteur (optionnel)"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent_lien',
            field=models.CharField(max_length=20, choices=[('pere', 'Père'), ('mere', 'Mère'), ('grand_parent', 'Grand-parent'), ('oncle_tante', 'Oncle/Tante'), ('frere_soeur', 'Frère/Sœur'), ('autre_famille', 'Autre membre de la famille'), ('tuteur_legal', 'Tuteur légal'), ('autre', 'Autre')], verbose_name="Lien avec l'élève", help_text="Lien de parenté du parent/tuteur avec l'élève"),
        ),
    ]
