# Generated by Django 5.2.6 on 2025-10-05 18:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0049_simplify_parent_tuteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description de la dépense', max_length=200, verbose_name='Description')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant de la dépense en FCFA', max_digits=10, verbose_name='Montant')),
                ('categorie', models.CharField(choices=[('personnel', 'Personnel'), ('equipement', 'Équipement'), ('maintenance', 'Maintenance'), ('formation', 'Formation'), ('marketing', 'Marketing'), ('bureau', 'Bureau'), ('transport', 'Transport'), ('loyer', 'Loyer'), ('autre', 'Autre')], help_text='Catégorie de la dépense', max_length=20, verbose_name='Catégorie')),
                ('date_depense', models.DateField(help_text='Date à laquelle la dépense a été effectuée', verbose_name='Date de la dépense')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('paye', 'Payé')], default='en_attente', help_text='Statut de la dépense', max_length=20, verbose_name='Statut')),
                ('fournisseur', models.CharField(help_text='Nom du fournisseur ou bénéficiaire', max_length=100, verbose_name='Fournisseur')),
                ('mode_paiement', models.CharField(blank=True, choices=[('virement', 'Virement'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('autre', 'Autre')], help_text='Mode de paiement utilisé', max_length=20, null=True, verbose_name='Mode de paiement')),
                ('reference_paiement', models.CharField(blank=True, help_text='Numéro de chèque, référence de virement, etc.', max_length=100, null=True, verbose_name='Référence de paiement')),
                ('piece_jointe', models.FileField(blank=True, help_text='Facture, reçu ou autre document justificatif', null=True, upload_to='depenses/', verbose_name='Pièce jointe')),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles sur la dépense', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('etablissement', models.ForeignKey(blank=True, help_text='Établissement concerné par cette dépense (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_creation'],
            },
        ),
    ]
