# Generated by Django 5.2.6 on 2025-10-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0050_depense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='reference_paiement',
        ),
    ]
