# Generated by Django 5.2.6 on 2025-10-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0051_remove_depense_reference_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='mode_paiement',
        ),
    ]
