# Generated by Django 5.2.6 on 2025-10-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0052_remove_depense_mode_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom ou description du budget', max_length=200, verbose_name='Nom du budget')),
                ('categorie', models.CharField(choices=[('personnel', 'Personnel'), ('equipement', 'Équipement'), ('maintenance', 'Maintenance'), ('formation', 'Formation'), ('marketing', 'Marketing'), ('bureau', 'Bureau'), ('transport', 'Transport'), ('loyer', 'Loyer'), ('autre', 'Autre')], help_text='Catégorie de dépense concernée', max_length=20, verbose_name='Catégorie')),
                ('montant_alloue', models.DecimalField(decimal_places=2, help_text='Montant alloué pour cette catégorie en FCFA', max_digits=12, verbose_name='Montant alloué')),
                ('periode', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], default='mensuel', help_text='Période de validité du budget', max_length=20, verbose_name='Période')),
                ('date_debut', models.DateField(help_text='Date de début de la période budgétaire', verbose_name='Date de début')),
                ('date_fin', models.DateField(help_text='Date de fin de la période budgétaire', verbose_name='Date de fin')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('actif', models.BooleanField(default=True, help_text='Indique si le budget est actif', verbose_name='Actif')),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles sur le budget', null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-date_creation'],
                'unique_together': {('categorie', 'date_debut', 'date_fin')},
            },
        ),
    ]
