# Generated by Django 5.2.6 on 2025-10-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0054_professeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='diplomes',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='experience_annees',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='notes_administratives',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='specialites',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='statut',
        ),
        migrations.AddField(
            model_name='professeur',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='matiere_principale',
            field=models.CharField(choices=[('mathematiques', 'Mathématiques'), ('francais', 'Français'), ('anglais', 'Anglais'), ('histoire_geo', 'Histoire-Géographie'), ('sciences', 'Sciences'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('biologie', 'Biologie'), ('sport', 'Éducation Physique et Sportive'), ('art', 'Arts Plastiques'), ('musique', 'Éducation Musicale'), ('technologie', 'Technologie'), ('informatique', 'Informatique'), ('philosophie', 'Philosophie'), ('economie', 'Économie'), ('autre', 'Autre')], max_length=50, verbose_name='Matière principale'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='matieres_secondaires',
            field=models.JSONField(blank=True, default=list, verbose_name='Matières secondaires'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
