# Generated by Django 5.2.6 on 2025-10-11 03:15

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0055_remove_professeur_cv_remove_professeur_diplomes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
