# Generated by Django 5.2.6 on 2025-10-11 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0056_alter_professeur_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la matière')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code de la matière')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('niveau_enseignement', models.CharField(choices=[('maternelle', 'Maternelle'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('superieur', 'Supérieur')], max_length=20, verbose_name="Niveau d'enseignement")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classes', models.ManyToManyField(blank=True, related_name='matieres', to='school_admin.classe', verbose_name='Classes concernées')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['niveau_enseignement', 'nom'],
                'unique_together': {('nom', 'etablissement', 'niveau_enseignement')},
            },
        ),
    ]
