# Generated by Django 5.2.6 on 2025-10-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0057_matiere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matiere',
            options={'ordering': ['nom'], 'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('nom', 'etablissement')},
        ),
        migrations.AddField(
            model_name='matiere',
            name='coefficient',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='Coefficient'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='couleur',
            field=models.CharField(default='#3b82f6', max_length=7, verbose_name="Couleur d'affichage"),
        ),
        migrations.AddField(
            model_name='matiere',
            name='heures_semaine',
            field=models.PositiveIntegerField(default=0, verbose_name='Heures par semaine'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='niveau',
            field=models.CharField(choices=[('maternelle', 'Maternelle'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('superieur', 'Supérieur'), ('tous', 'Tous niveaux')], default='tous', max_length=20, verbose_name="Niveau d'enseignement"),
        ),
        migrations.AddField(
            model_name='matiere',
            name='type_matiere',
            field=models.CharField(choices=[('obligatoire', 'Matière obligatoire'), ('optionnelle', 'Matière optionnelle'), ('facultative', 'Matière facultative'), ('sport', 'Éducation physique et sportive'), ('art', 'Arts et culture'), ('technique', 'Matière technique')], default='obligatoire', max_length=20, verbose_name='Type de matière'),
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='niveau_enseignement',
        ),
    ]
