# Generated by Django 5.2.6 on 2025-10-11 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0058_alter_matiere_options_alter_matiere_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='couleur',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='heures_semaine',
        ),
    ]
