# Generated by Django 5.2.6 on 2025-10-11 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0059_remove_matiere_couleur_remove_matiere_heures_semaine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='matiere_principale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professeurs_principaux', to='school_admin.matiere', verbose_name='Matière principale'),
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='matieres_secondaires',
        ),
        migrations.AddField(
            model_name='professeur',
            name='matieres_secondaires',
            field=models.ManyToManyField(blank=True, related_name='professeurs_secondaires', to='school_admin.matiere', verbose_name='Matières secondaires'),
        ),
    ]
