# Generated by Django 5.2.6 on 2025-10-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0060_alter_professeur_matiere_principale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='professeurs', to='school_admin.classe', verbose_name='Classes affectées'),
        ),
    ]
