# Generated by Django 5.2.6 on 2025-10-11 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0061_professeur_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationProfesseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('principal', 'Professeur Principal'), ('classique', 'Professeur Classique')], default='classique', max_length=20, verbose_name='Statut')),
                ('date_affectation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'affectation")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='school_admin.classe', verbose_name='Classe')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='school_admin.professeur', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Affectation Professeur',
                'verbose_name_plural': 'Affectations Professeurs',
                'ordering': ['-date_affectation'],
                'unique_together': {('professeur', 'classe')},
            },
        ),
    ]
