# Generated by Django 5.2.6 on 2025-10-11 14:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0062_affectationprofesseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la salle')),
                ('numero', models.CharField(max_length=20, verbose_name='Numéro de salle')),
                ('type_salle', models.CharField(choices=[('classe', 'Salle de Classe'), ('laboratoire', 'Laboratoire'), ('bibliotheque', 'Bibliothèque'), ('salle_informatique', "Salle d'Informatique"), ('salle_art', "Salle d'Arts"), ('salle_musique', 'Salle de Musique'), ('salle_sport', 'Salle de Sport'), ('amphitheatre', 'Amphithéâtre'), ('salle_reunion', 'Salle de Réunion'), ('bureau', 'Bureau'), ('autre', 'Autre')], default='classe', max_length=20, verbose_name='Type de salle')),
                ('capacite_max', models.PositiveIntegerField(default=30, verbose_name='Capacité maximale')),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Superficie (m²)')),
                ('equipements', models.TextField(blank=True, help_text='Liste des équipements disponibles dans la salle', null=True, verbose_name='Équipements disponibles')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('etat', models.CharField(choices=[('disponible', 'Disponible'), ('occupee', 'Occupée'), ('maintenance', 'En Maintenance'), ('fermee', 'Fermée')], default='disponible', max_length=15, verbose_name='État de la salle')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['numero', 'nom'],
                'unique_together': {('numero', 'etablissement')},
            },
        ),
    ]
