# Generated by Django 5.2.6 on 2025-10-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0063_salle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='equipements',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='superficie',
        ),
    ]
