# Generated by Django 5.2.6 on 2025-10-11 16:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0064_remove_salle_description_remove_salle_equipements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10, verbose_name='Jour de la semaine')),
                ('periode', models.CharField(choices=[('matin', 'Matin'), ('apres_midi', 'Après-midi'), ('soir', 'Soir'), ('journee_complete', 'Journée complète')], default='journee_complete', max_length=20, verbose_name='Période')),
                ('heure_debut', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('temporaire', 'Temporaire')], default='active', max_length=10, verbose_name='Statut')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_debut', models.DateField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire sur cette affectation', null=True, verbose_name='Commentaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_salles', to='school_admin.classe', verbose_name='Classe')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_classes', to='school_admin.salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Affectation Salle',
                'verbose_name_plural': 'Affectations Salles',
                'ordering': ['classe__nom', 'jour_semaine', 'periode'],
                'unique_together': {('classe', 'salle', 'jour_semaine', 'periode', 'actif')},
            },
        ),
    ]
