# Generated by Django 5.2.6 on 2025-10-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0065_affectationsalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectationsalle',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='affectationsalle',
            name='date_fin',
        ),
    ]
