# Generated by Django 5.2.6 on 2025-10-14 16:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0066_remove_date_fields_from_affectation_salle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etablissement',
            options={'managed': True, 'ordering': ['-date_creation'], 'verbose_name': 'Établissement', 'verbose_name_plural': 'Établissements'},
        ),
        migrations.AlterModelTable(
            name='etablissement',
            table='school_admin_etablissement',
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(help_text='Ex: 2023-2024', max_length=20, verbose_name='Année scolaire')),
                ('est_actif', models.BooleanField(default=True, help_text='Indique si cet emploi du temps est actuellement utilisé', verbose_name='Actif')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('notes', models.TextField(blank=True, help_text='Notes ou commentaires sur cet emploi du temps', null=True, verbose_name='Notes')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='school_admin.classe', verbose_name='Classe')),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
                'ordering': ['-est_actif', '-date_creation'],
                'unique_together': {('classe', 'annee_scolaire', 'est_actif')},
            },
        ),
        migrations.CreateModel(
            name='CreneauEmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10, verbose_name='Jour')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('type_cours', models.CharField(choices=[('cours', 'Cours'), ('td', 'Travaux Dirigés'), ('tp', 'Travaux Pratiques'), ('controle', 'Contrôle'), ('examen', 'Examen'), ('sport', 'Sport'), ('pause', 'Pause'), ('autre', 'Autre')], default='cours', max_length=20, verbose_name='Type de cours')),
                ('couleur', models.CharField(default='#3b82f6', help_text="Code couleur hexadécimal pour l'affichage", max_length=7, verbose_name='Couleur')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux_emploi_temps', to='school_admin.matiere', verbose_name='Matière')),
                ('professeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux_emploi_temps', to='school_admin.professeur', verbose_name='Professeur')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux_emploi_temps', to='school_admin.salle', verbose_name='Salle')),
                ('emploi_du_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='school_admin.emploidutemps', verbose_name='Emploi du temps')),
            ],
            options={
                'verbose_name': "Créneau d'emploi du temps",
                'verbose_name_plural': "Créneaux d'emploi du temps",
                'ordering': ['jour', 'heure_debut'],
            },
        ),
    ]
