# Generated by Django 5.2.6 on 2025-10-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0067_alter_etablissement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='mot_de_passe_provisoire',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mot de passe provisoire'),
        ),
    ]
