# Generated by Django 5.2.6 on 2025-10-15 05:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0070_remove_coefficient_from_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moyenne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('trimestre1', 'Trimestre 1'), ('trimestre2', 'Trimestre 2'), ('trimestre3', 'Trimestre 3'), ('semestre1', 'Semestre 1'), ('semestre2', 'Semestre 2'), ('annee', 'Année')], default='trimestre1', max_length=20, verbose_name='Période')),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Moyenne sur 20')),
                ('nombre_notes', models.PositiveIntegerField(default=0, verbose_name='Nombre de notes utilisées')),
                ('date_calcul', models.DateTimeField(auto_now=True, verbose_name='Date du calcul')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes', to='school_admin.classe', verbose_name='Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes', to='school_admin.eleve', verbose_name='Élève')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes', to='school_admin.matiere', verbose_name='Matière')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_calculees', to='school_admin.professeur', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Moyenne',
                'verbose_name_plural': 'Moyennes',
                'ordering': ['-date_calcul'],
                'unique_together': {('eleve', 'classe', 'matiere', 'periode')},
            },
        ),
    ]
