# Generated by Django 5.2.6 on 2025-10-15 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0071_add_moyenne_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('trimestre1', 'Trimestre 1'), ('trimestre2', 'Trimestre 2'), ('trimestre3', 'Trimestre 3'), ('annuel', 'Annuel')], default='trimestre1', max_length=20, verbose_name='Période')),
                ('soumis', models.BooleanField(default=False, verbose_name='Soumis')),
                ('date_soumission', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_notes', to='school_admin.classe', verbose_name='Classe')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_etablissement', to='school_admin.etablissement', verbose_name='Établissement')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_matiere', to='school_admin.matiere', verbose_name='Matière')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_soumis', to='school_admin.professeur', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Relevé de notes',
                'verbose_name_plural': 'Relevés de notes',
                'ordering': ['-date_creation'],
                'unique_together': {('classe', 'professeur', 'matiere', 'periode')},
            },
        ),
    ]
