# Generated by Django 5.2.6 on 2025-10-15 16:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0073_evaluation_periode_alter_moyenne_periode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date')),
                ('validee', models.BooleanField(default=False, verbose_name='Liste validée')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('nombre_presents', models.IntegerField(default=0, verbose_name='Nombre de présents')),
                ('nombre_absents', models.IntegerField(default=0, verbose_name="Nombre d'absents")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listes_presences', to='school_admin.classe', verbose_name='Classe')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listes_presences', to='school_admin.etablissement', verbose_name='Établissement')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listes_presences', to='school_admin.professeur', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Liste de présence',
                'verbose_name_plural': 'Listes de présence',
                'ordering': ['-date', 'classe__nom'],
                'unique_together': {('classe', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'Retard'), ('absent_justifie', 'Absent Justifié')], default='present', max_length=20, verbose_name='Statut')),
                ('remarque', models.TextField(blank=True, null=True, verbose_name='Remarque')),
                ('heure_enregistrement', models.TimeField(auto_now_add=True, verbose_name="Heure d'enregistrement")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='school_admin.classe', verbose_name='Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='school_admin.eleve', verbose_name='Élève')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='school_admin.etablissement', verbose_name='Établissement')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences_prises', to='school_admin.professeur', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date', 'eleve__nom', 'eleve__prenom'],
                'indexes': [models.Index(fields=['date', 'classe'], name='school_admi_date_b741f3_idx'), models.Index(fields=['eleve', 'date'], name='school_admi_eleve_i_f1d1e1_idx')],
                'unique_together': {('eleve', 'classe', 'date')},
            },
        ),
    ]
