# Generated by Django 5.2.6 on 2025-10-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0074_listepresence_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='date_justification',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de justification'),
        ),
        migrations.AddField(
            model_name='presence',
            name='justificatif_valide',
            field=models.BooleanField(default=False, verbose_name='Justificatif validé'),
        ),
        migrations.AddField(
            model_name='presence',
            name='type_justificatif',
            field=models.CharField(blank=True, choices=[('certificat_medical', 'Certificat médical'), ('raison_familiale', 'Raison familiale'), ('deces_famille', 'Décès dans la famille'), ('maladie', 'Maladie (sans certificat)'), ('rendez_vous_medical', 'Rendez-vous médical'), ('evenement_religieux', 'Événement religieux'), ('probleme_transport', 'Problème de transport'), ('autre', 'Autre raison')], max_length=30, null=True, verbose_name='Type de justificatif'),
        ),
    ]
