# Generated by Django 5.2.6 on 2025-10-15 18:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0075_presence_date_justification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sanction', models.CharField(choices=[('avertissement', 'Avertissement'), ('blame', 'Blâme'), ('exclusion_cours', 'Exclusion de cours'), ('exclusion_temporaire', 'Exclusion temporaire'), ('travaux_interet_general', "Travaux d'intérêt général"), ('retenue', 'Retenue'), ('convocation_parents', 'Convocation des parents'), ('avertissement_conduite', 'Avertissement de conduite')], max_length=30, verbose_name='Type de sanction')),
                ('raison', models.CharField(choices=[('indiscipline', 'Indiscipline'), ('absence_non_justifiee', 'Absence non justifiée répétée'), ('retards_repetes', 'Retards répétés'), ('manque_respect', 'Manque de respect envers le personnel'), ('violence', 'Violence physique ou verbale'), ('triche', "Tricherie lors d'une évaluation"), ('desobeissance', 'Désobéissance'), ('perturbation_cours', 'Perturbation du cours'), ('degradation_materiel', 'Dégradation du matériel'), ('vol', 'Vol'), ('comportement_inapproprie', 'Comportement inapproprié'), ('non_respect_reglement', 'Non-respect du règlement intérieur'), ('autre', 'Autre raison')], max_length=40, verbose_name='Raison de la sanction')),
                ('gravite', models.CharField(choices=[('legere', 'Légère'), ('moyenne', 'Moyenne'), ('grave', 'Grave'), ('tres_grave', 'Très grave')], default='moyenne', max_length=20, verbose_name='Gravité')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description détaillée')),
                ('date_sanction', models.DateField(default=django.utils.timezone.now, verbose_name='Date de la sanction')),
                ('duree_jours', models.IntegerField(blank=True, help_text='Pour exclusions temporaires ou retenues', null=True, verbose_name='Durée (en jours)')),
                ('date_debut_execution', models.DateField(blank=True, null=True, verbose_name="Date de début d'exécution")),
                ('date_fin_execution', models.DateField(blank=True, null=True, verbose_name="Date de fin d'exécution")),
                ('executee', models.BooleanField(default=False, verbose_name='Sanction exécutée')),
                ('date_execution', models.DateTimeField(blank=True, null=True, verbose_name="Date d'exécution")),
                ('parents_informes', models.BooleanField(default=False, verbose_name='Parents informés')),
                ('date_information_parents', models.DateTimeField(blank=True, null=True, verbose_name="Date d'information des parents")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='school_admin.classe', verbose_name='Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='school_admin.eleve', verbose_name='Élève')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='school_admin.etablissement', verbose_name='Établissement')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions_donnees', to='school_admin.professeur', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Sanction',
                'verbose_name_plural': 'Sanctions',
                'ordering': ['-date_sanction', '-date_creation'],
            },
        ),
    ]
