# Generated by Django 5.2.6 on 2025-10-16 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0076_sanction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanction',
            name='attribue_par_nom',
            field=models.CharField(default='Système', help_text='Nom complet de la personne ayant attribué la sanction', max_length=200, verbose_name='Attribué par (nom)'),
        ),
        migrations.AddField(
            model_name='sanction',
            name='attribue_par_type',
            field=models.CharField(choices=[('professeur', 'Professeur'), ('directeur', 'Directeur')], default='professeur', max_length=20, verbose_name='Attribué par (type)'),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanctions_donnees', to='school_admin.professeur', verbose_name='Professeur'),
        ),
    ]
