# Generated by Django 5.2.6 on 2025-10-19 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0077_sanction_attribue_par_nom_sanction_attribue_par_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affectationprofesseur',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='affectationprofesseur',
            name='matiere',
            field=models.ForeignKey(blank=True, help_text='Matière que le professeur enseigne dans cette classe', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='school_admin.matiere', verbose_name='Matière enseignée'),
        ),
        migrations.AlterUniqueTogether(
            name='affectationprofesseur',
            unique_together={('professeur', 'classe', 'matiere')},
        ),
    ]
