# Generated by Django 5.2.6 on 2025-10-20 15:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0078_alter_affectationprofesseur_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneauemploidutemps',
            name='heure_debut',
            field=models.TimeField(blank=True, help_text="Laissez vide pour utiliser l'heure de la période d'établissement", null=True, verbose_name='Heure de début'),
        ),
        migrations.AlterField(
            model_name='creneauemploidutemps',
            name='heure_fin',
            field=models.TimeField(blank=True, help_text="Laissez vide pour utiliser l'heure de la période d'établissement", null=True, verbose_name='Heure de fin'),
        ),
        migrations.CreateModel(
            name='ConfigurationHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut_cours', models.TimeField(help_text='Ex: 08:00', verbose_name='Heure de début des cours')),
                ('heure_fin_cours', models.TimeField(help_text='Ex: 16:00', verbose_name='Heure de fin des cours')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Configuration active')),
                ('etablissement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_horaire', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Configuration horaire',
                'verbose_name_plural': 'Configurations horaires',
            },
        ),
        migrations.CreateModel(
            name='PeriodeEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Période 1, Récréation, Pause déjeuner', max_length=100, verbose_name='Nom de la période')),
                ('type_periode', models.CharField(choices=[('cours', 'Période de cours'), ('pause', 'Pause/Récréation'), ('dejeuner', 'Pause déjeuner')], max_length=20, verbose_name='Type de période')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('ordre', models.IntegerField(help_text="Détermine l'ordre d'affichage dans l'emploi du temps", verbose_name="Ordre d'affichage")),
                ('jours', models.CharField(blank=True, help_text="Si vide, s'applique à tous les jours. Format: lundi,mardi,...", max_length=255, null=True, verbose_name='Jours concernés')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('configuration_horaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='school_admin.configurationhoraire', verbose_name='Configuration horaire')),
            ],
            options={
                'verbose_name': "Période d'établissement",
                'verbose_name_plural': "Périodes d'établissement",
                'ordering': ['ordre', 'heure_debut'],
                'unique_together': {('configuration_horaire', 'nom', 'heure_debut')},
            },
        ),
        migrations.AddField(
            model_name='creneauemploidutemps',
            name='periode_etablissement',
            field=models.ForeignKey(blank=True, help_text="Période standard de l'établissement (recommandé)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux', to='school_admin.periodeetablissement', verbose_name="Période de l'établissement"),
        ),
    ]
