# Generated by Django 5.2.6 on 2025-10-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0079_alter_creneauemploidutemps_heure_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneauemploidutemps',
            name='groupe_creneau',
            field=models.CharField(blank=True, help_text="Identifiant unique pour regrouper plusieurs créneaux d'un même cours", max_length=50, null=True, verbose_name='Groupe de créneau'),
        ),
    ]
