# Generated by Django 5.2.6 on 2025-10-20 21:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('school_admin', '0080_add_groupe_creneau'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='matricule_eleve',
            field=models.CharField(blank=True, help_text="Matricule de connexion de l'élève (ex: BP2025001)", max_length=20, null=True, unique=True, verbose_name='Matricule élève'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='mot_de_passe_eleve_modifie',
            field=models.BooleanField(default=False, help_text="Indique si l'élève a changé son mot de passe initial", verbose_name='Mot de passe élève modifié'),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('matricule_parental', models.CharField(help_text='Identifiant unique du parent (ex: BPP2025001)', max_length=20, unique=True, verbose_name='Matricule parental')),
                ('type_parent', models.CharField(choices=[('mere', 'Mère'), ('pere', 'Père'), ('tuteur', 'Tuteur/Tutrice')], max_length=10, verbose_name='Type de parent')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('mot_de_passe_provisoire', models.CharField(help_text='Mot de passe initial à changer lors de la première connexion', max_length=10, verbose_name='Mot de passe provisoire')),
                ('mot_de_passe_modifie', models.BooleanField(default=False, help_text='Indique si le parent a changé son mot de passe initial', verbose_name='Mot de passe modifié')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='school_admin.etablissement', verbose_name='Établissement')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='parent_set', related_query_name='parent', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='parent_set', related_query_name='parent', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': "Parent d'élève",
                'verbose_name_plural': "Parents d'élèves",
                'ordering': ['-date_creation'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LienFamilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lien', models.CharField(choices=[('mere', 'Mère'), ('pere', 'Père'), ('tuteur', 'Tuteur/Tutrice')], max_length=10, verbose_name='Type de lien familial')),
                ('statut', models.CharField(choices=[('valide', 'Validé'), ('en_attente', 'En attente de validation'), ('refuse', 'Refusé')], default='valide', max_length=15, verbose_name='Statut')),
                ('est_inscripteur', models.BooleanField(default=False, help_text="Indique si c'est le parent qui a inscrit l'élève initialement", verbose_name='Parent inscripteur')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_parents', to='school_admin.eleve', verbose_name='Élève')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_enfants', to='school_admin.parent', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Lien familial',
                'verbose_name_plural': 'Liens familiaux',
                'ordering': ['-date_creation'],
                'unique_together': {('parent', 'eleve')},
            },
        ),
        migrations.CreateModel(
            name='DemandeLiaisonParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_eleve', models.CharField(help_text="Matricule unique de l'élève (ex: BP2025001)", max_length=20, verbose_name="Matricule de l'élève")),
                ('nom_eleve', models.CharField(max_length=100, verbose_name="Nom de l'élève")),
                ('prenom_eleve', models.CharField(max_length=100, verbose_name="Prénom de l'élève")),
                ('date_naissance_eleve', models.DateField(help_text="Pour vérification de l'identité", verbose_name="Date de naissance de l'élève")),
                ('type_lien', models.CharField(choices=[('mere', 'Mère'), ('pere', 'Père'), ('tuteur', 'Tuteur/Tutrice')], max_length=10, verbose_name='Type de lien familial')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée')], default='en_attente', max_length=15, verbose_name='Statut de la demande')),
                ('justificatif', models.FileField(blank=True, help_text='Document prouvant le lien familial (acte de naissance, livret de famille, etc.)', null=True, upload_to='justificatifs_liaison/%Y/%m/', verbose_name='Justificatif')),
                ('message', models.TextField(blank=True, help_text='Message explicatif du parent', verbose_name='Message')),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la demande')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('motif_refus', models.TextField(blank=True, help_text='Raison du refus de la demande', verbose_name='Motif du refus')),
                ('eleve_valide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_liaison_recues', to='school_admin.eleve', verbose_name='Élève validé')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to='school_admin.personneladministratif', verbose_name='Traité par')),
                ('parent_demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_liaison', to='school_admin.parent', verbose_name='Parent demandeur')),
            ],
            options={
                'verbose_name': 'Demande de liaison parent',
                'verbose_name_plural': 'Demandes de liaison parent',
                'ordering': ['-date_demande'],
                'indexes': [models.Index(fields=['statut', '-date_demande'], name='school_admi_statut_a0ac8c_idx'), models.Index(fields=['matricule_eleve'], name='school_admi_matricu_356657_idx')],
            },
        ),
    ]
