# Generated by Django 5.2.6 on 2025-10-21 00:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0081_eleve_matricule_eleve_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_periode', models.CharField(choices=[('trimestre1', '1er Trimestre'), ('trimestre2', '2ème Trimestre'), ('trimestre3', '3ème Trimestre'), ('semestre1', '1er Semestre'), ('semestre2', '2ème Semestre'), ('annee', 'Année complète')], help_text='Type de période scolaire', max_length=50, verbose_name='Nom de la période')),
                ('date_debut', models.DateField(help_text='Date de début de la période', verbose_name='Date de début')),
                ('date_fin', models.DateField(help_text='Date de fin de la période', verbose_name='Date de fin')),
                ('annee_scolaire', models.CharField(help_text='Format: YYYY-YYYY (ex: 2025-2026)', max_length=20, verbose_name='Année scolaire')),
                ('est_active', models.BooleanField(default=True, help_text='Indique si cette période est actuellement active', verbose_name='Période active')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Période scolaire',
                'verbose_name_plural': 'Périodes scolaires',
                'ordering': ['date_debut'],
                'unique_together': {('etablissement', 'nom_periode', 'annee_scolaire')},
            },
        ),
    ]
