# Generated by Django 5.2.6 on 2025-10-21 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0082_periode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_periode', models.CharField(help_text='Ex: 1er Trimestre, Semestre 1', max_length=100, verbose_name='Nom de la période')),
                ('type_periode', models.CharField(choices=[('trimestre', 'Trimestre'), ('semestre', 'Semestre'), ('annee', 'Année complète')], default='trimestre', max_length=20, verbose_name='Type de période')),
                ('date_debut', models.DateField(help_text='Date de début de la période', verbose_name='Date de début')),
                ('date_fin', models.DateField(help_text='Date de fin de la période', verbose_name='Date de fin')),
                ('annee_scolaire', models.CharField(help_text='Ex: 2025-2026', max_length=20, verbose_name='Année scolaire')),
                ('est_active', models.BooleanField(default=True, help_text='Indique si cette période est actuellement active', verbose_name='Période active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes_scolaires', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Période scolaire',
                'verbose_name_plural': 'Périodes scolaires',
                'ordering': ['annee_scolaire', 'date_debut'],
                'unique_together': {('etablissement', 'nom_periode', 'annee_scolaire')},
            },
        ),
        migrations.DeleteModel(
            name='Periode',
        ),
    ]
