# Generated by Django 5.2.6 on 2025-10-21 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0084_remove_evaluation_periode_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relevenotes',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='relevenotes',
            name='periode_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releves_notes', to='school_admin.periodescolaire', verbose_name='Période scolaire'),
        ),
        migrations.RemoveField(
            model_name='relevenotes',
            name='periode',
        ),
    ]
