# Generated by Django 5.2.6 on 2025-10-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0085_alter_relevenotes_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moyenne',
            name='evaluations_utilisees',
            field=models.JSONField(blank=True, default=list, verbose_name='IDs des évaluations utilisées dans le calcul'),
        ),
        migrations.AddField(
            model_name='moyenne',
            name='mode_calcul',
            field=models.CharField(default='toutes', max_length=20, verbose_name='Mode de calcul (toutes, 2, 3, 4)'),
        ),
    ]
