# Generated by Django 5.2.6 on 2025-10-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0086_moyenne_evaluations_utilisees_moyenne_mode_calcul'),
    ]

    operations = [
        migrations.AddField(
            model_name='moyenne',
            name='details_notes',
            field=models.JSONField(blank=True, default=list, verbose_name='Détails des notes utilisées (valeurs, titres, barèmes)'),
        ),
    ]
