# Generated by Django 5.2.6 on 2025-10-21 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0087_moyenne_details_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_examen', models.CharField(help_text='Ex: Examen de Mathématiques, Devoir surveillé de Français', max_length=200, verbose_name="Nom de l'examen")),
                ('date_debut', models.DateField(verbose_name='Date de début de la session')),
                ('date_fin', models.DateField(verbose_name='Date de fin de la session')),
                ('description', models.TextField(blank=True, help_text='Instructions ou informations supplémentaires', null=True, verbose_name='Description')),
                ('duree_totale', models.DurationField(blank=True, help_text="Durée totale de la session d'examens", null=True, verbose_name='Durée totale estimée')),
                ('est_publie', models.BooleanField(default=False, help_text="L'examen est-il visible par les élèves et parents ?", verbose_name='Publié')),
                ('est_annule', models.BooleanField(default=False, verbose_name='Annulé')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('classes', models.ManyToManyField(related_name='sessions_examens', to='school_admin.classe', verbose_name='Classes concernées')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_examens', to='school_admin.etablissement', verbose_name='Établissement')),
                ('matieres', models.ManyToManyField(related_name='sessions_examens', to='school_admin.matiere', verbose_name="Matières de l'examen")),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_examens', to='school_admin.periodescolaire', verbose_name='Période scolaire')),
            ],
            options={
                'verbose_name': "Session d'examen",
                'verbose_name_plural': "Sessions d'examens",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CreneauExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_examen', models.DateField(verbose_name="Date de l'examen")),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('consignes_specifiques', models.TextField(blank=True, help_text='Instructions particulières pour ce créneau', null=True, verbose_name='Consignes spécifiques')),
                ('duree_estimee', models.DurationField(blank=True, null=True, verbose_name='Durée estimée')),
                ('est_confirme', models.BooleanField(default=False, verbose_name='Créneau confirmé')),
                ('est_annule', models.BooleanField(default=False, verbose_name='Créneau annulé')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux_examens', to='school_admin.matiere', verbose_name='Matière')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux_examens', to='school_admin.salle', verbose_name='Salle principale')),
                ('surveillant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux_surveillance', to='school_admin.professeur', verbose_name='Surveillant principal')),
                ('session_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='school_admin.sessionexamen', verbose_name="Session d'examen")),
            ],
            options={
                'verbose_name': "Créneau d'examen",
                'verbose_name_plural': "Créneaux d'examens",
                'ordering': ['date_examen', 'heure_debut'],
                'unique_together': {('session_examen', 'matiere', 'date_examen')},
            },
        ),
    ]
