# Generated by Django 5.2.6 on 2025-10-21 18:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0088_sessionexamen_creneauexamen'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note sur 20')),
                ('bareme', models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Barème')),
                ('note_sur_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note ramenée sur 20')),
                ('absent', models.BooleanField(default=False, verbose_name='Élève absent')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire/Appréciation')),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_examens', to='school_admin.classe', verbose_name='Classe')),
                ('creneau_examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='school_admin.creneauexamen', verbose_name="Créneau d'examen")),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_examens', to='school_admin.eleve', verbose_name='Élève')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_examens', to='school_admin.matiere', verbose_name='Matière')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_examens_saisies', to='school_admin.professeur', verbose_name='Professeur')),
                ('session_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='school_admin.sessionexamen', verbose_name="Session d'examen")),
            ],
            options={
                'verbose_name': "Note d'examen",
                'verbose_name_plural': "Notes d'examens",
                'ordering': ['-date_saisie'],
                'unique_together': {('eleve', 'session_examen', 'matiere')},
            },
        ),
    ]
