# Generated by Django 5.2.6 on 2025-10-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0089_noteexamen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteexamen',
            name='date_soumission',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission'),
        ),
        migrations.AddField(
            model_name='noteexamen',
            name='soumis',
            field=models.BooleanField(default=False, verbose_name='Note soumise (verrouillée)'),
        ),
    ]
