# Generated by Django 5.2.6 on 2025-10-24 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0090_noteexamen_date_soumission_noteexamen_soumis'),
    ]

    operations = [
        migrations.AddField(
            model_name='personneladministratif',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='Permissions'),
        ),
        migrations.AddField(
            model_name='personneladministratif',
            name='section',
            field=models.CharField(blank=True, choices=[('direction', 'Direction'), ('administration', 'Administration'), ('pedagogie', 'Pédagogie'), ('vie_scolaire', 'Vie Scolaire')], max_length=20, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='personneladministratif',
            name='superviseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordonnes', to='school_admin.personneladministratif', verbose_name='Superviseur hiérarchique'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='type_etablissement',
            field=models.CharField(choices=[('primary', 'École Primaire'), ('collège', 'Collège'), ('lycée', 'Lycée'), ('mixte', 'Établissement Mixte')], max_length=20, verbose_name="Type d'établissement"),
        ),
        migrations.AlterField(
            model_name='personneladministratif',
            name='fonction',
            field=models.CharField(choices=[('directeur_primaire', 'Directeur (École Primaire)'), ('directeur_adjoint_primaire', 'Directeur Adjoint (École Primaire)'), ('principal', 'Principal (Collège)'), ('principal_adjoint', 'Principal Adjoint (Collège)'), ('proviseur', 'Proviseur (Lycée)'), ('proviseur_adjoint', 'Proviseur Adjoint (Lycée)'), ('directeur_principal', 'Directeur Principal (Établissement Mixte)'), ('directeur_section_primaire', 'Directeur de Section Primaire'), ('principal_section_college', 'Principal de Section Collège'), ('proviseur_section_lycee', 'Proviseur de Section Lycée'), ('secretaire_principal', 'Secrétaire Principal'), ('secretaire', 'Secrétaire'), ('comptable', 'Comptable'), ('econome', 'Économe'), ('gestionnaire', 'Gestionnaire'), ('censeur', 'Censeur'), ('censeur_adjoint', 'Censeur Adjoint'), ('censeur_etudes', 'Censeur des Études'), ('chef_departement', 'Chef de Département'), ('coordonnateur_cycle', 'Coordonnateur de Cycle'), ('surveillant_general', 'Surveillant Général'), ('surveillant_adjoint', 'Surveillant Adjoint'), ('surveillant', 'Surveillant'), ('secretaire_vie_scolaire', 'Secrétaire de Vie Scolaire'), ('administrateur', 'Administrateur Système')], max_length=50, verbose_name='Fonction'),
        ),
    ]
