# Generated by Django 5.2.6 on 2025-10-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0091_add_personnel_modulaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personneladministratif',
            name='section',
        ),
        migrations.RemoveField(
            model_name='personneladministratif',
            name='superviseur',
        ),
        migrations.AddField(
            model_name='personneladministratif',
            name='mot_de_passe_provisoire',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mot de passe provisoire (en clair)'),
        ),
        migrations.AlterField(
            model_name='personneladministratif',
            name='fonction',
            field=models.CharField(choices=[('directeur_adjoint_primaire', 'Directeur Adjoint (École Primaire)'), ('principal', 'Principal (Collège)'), ('principal_adjoint', 'Principal Adjoint (Collège)'), ('proviseur', 'Proviseur (Lycée)'), ('proviseur_adjoint', 'Proviseur Adjoint (Lycée)'), ('directeur_principal', 'Directeur Principal (Établissement Mixte)'), ('directeur_section_primaire', 'Directeur de Section Primaire'), ('principal_section_college', 'Principal de Section Collège'), ('proviseur_section_lycee', 'Proviseur de Section Lycée'), ('secretaire_principal', 'Secrétaire Principal'), ('secretaire', 'Secrétaire'), ('comptable', 'Comptable'), ('econome', 'Économe'), ('gestionnaire', 'Gestionnaire'), ('censeur', 'Censeur'), ('censeur_etudes', 'Censeur des Études (Collèges & Lycées)'), ('censeur_adjoint', 'Censeur Adjoint (Lycées)'), ('censeur_premier_cycle', 'Censeur du Premier Cycle (6e à 3e)'), ('censeur_second_cycle', 'Censeur du Second Cycle (2nde à Tle)'), ('censeur_pedagogie', 'Censeur chargé de la Pédagogie'), ('censeur_vie_scolaire', 'Censeur chargé de la Vie Scolaire'), ('chef_departement', 'Chef de Département'), ('surveillant_general', 'Surveillant Général'), ('surveillant_adjoint', 'Surveillant Adjoint'), ('surveillant', 'Surveillant'), ('secretaire_vie_scolaire', 'Secrétaire de Vie Scolaire'), ('administrateur', 'Administrateur Système')], max_length=50, verbose_name='Fonction'),
        ),
    ]
