# Generated by Django 5.2.6 on 2025-10-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0092_modifier_personnel_censeurs_mdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='type_etablissement',
            field=models.CharField(choices=[('primary', 'École Primaire'), ('collège', 'Collège'), ('lycée', 'Lycée'), ('collège_lycée', 'Collège + Lycée'), ('mixte', 'Établissement Mixte (Primaire + Collège + Lycée)')], max_length=20, verbose_name="Type d'établissement"),
        ),
    ]
