# Generated by Django 5.2.6 on 2025-10-25 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0098_evaluation_matiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='matieres_enseignees_primaire',
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='matiere',
            field=models.ForeignKey(blank=True, help_text="Matière de l'évaluation (pour le primaire multi-matières)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='school_admin.matiere', verbose_name='Matière'),
        ),
    ]
