# Generated by Django 5.2.6 on 2025-10-25 15:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0100_remove_evaluation_matiere_evaluationprimaire_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluationprimaire',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='evaluationprimaire',
            name='type_evaluation',
            field=models.CharField(choices=[('controle', 'Contrôle écrit'), ('interrogation', 'Interrogation'), ('devoir_maison', 'Devoir maison'), ('projet', 'Projet'), ('oral', 'Évaluation orale'), ('pratique', 'Évaluation pratique'), ('composition', 'Composition')], default='controle', max_length=20, verbose_name="Type d'évaluation"),
        ),
        migrations.CreateModel(
            name='AffectationProfesseurPrimaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('principal', 'Professeur Principal'), ('polyvalent', 'Professeur Polyvalent')], default='polyvalent', max_length=20, verbose_name='Statut')),
                ('date_affectation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'affectation")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_primaire', to='school_admin.classe', verbose_name='Classe')),
                ('matieres', models.ManyToManyField(help_text='Toutes les matières que le professeur enseigne dans cette classe', related_name='affectations_primaire', to='school_admin.matiere', verbose_name='Matières enseignées')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_primaire', to='school_admin.professeur', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Affectation Professeur Primaire',
                'verbose_name_plural': 'Affectations Professeurs Primaire',
                'ordering': ['-date_affectation'],
                'unique_together': {('professeur', 'classe')},
            },
        ),
        migrations.CreateModel(
            name='MoyenneMatierePrimaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Moyenne sur 20')),
                ('nombre_notes', models.PositiveIntegerField(default=0, verbose_name='Nombre de notes')),
                ('appreciation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Appréciation')),
                ('date_calcul', models.DateTimeField(auto_now=True, verbose_name='Date de calcul')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_matieres_primaire', to='school_admin.classe', verbose_name='Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_matieres_primaire', to='school_admin.eleve', verbose_name='Élève')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_primaire', to='school_admin.matiere', verbose_name='Matière')),
                ('periode_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_matieres_primaire', to='school_admin.periodescolaire', verbose_name='Période scolaire')),
            ],
            options={
                'verbose_name': 'Moyenne Matière Primaire',
                'verbose_name_plural': 'Moyennes Matières Primaire',
                'ordering': ['eleve', 'matiere'],
                'unique_together': {('eleve', 'matiere', 'periode_scolaire')},
            },
        ),
        migrations.DeleteModel(
            name='MoyennePrimaire',
        ),
    ]
