# Generated by Django 5.2.7 on 2025-10-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0101_alter_evaluationprimaire_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moyennematiereprimaire',
            name='date_soumission',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission'),
        ),
        migrations.AddField(
            model_name='moyennematiereprimaire',
            name='soumis',
            field=models.BooleanField(default=False, help_text='Indique si cette moyenne a été soumise et verrouillée', verbose_name='Soumis'),
        ),
    ]
