# Generated by Django 5.2.7 on 2025-10-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0102_moyennematiereprimaire_date_soumission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteexamen',
            name='retenue',
            field=models.BooleanField(default=True, verbose_name='Note retenue pour la moyenne'),
        ),
        migrations.AddField(
            model_name='noteprimaire',
            name='retenue',
            field=models.BooleanField(default=True, verbose_name='Note retenue pour la moyenne'),
        ),
    ]
