# Generated by Django 5.2.7 on 2025-10-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0103_noteexamen_retenue_noteprimaire_retenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='retenue',
            field=models.BooleanField(default=False, verbose_name='Note retenue pour le calcul'),
        ),
        migrations.AlterField(
            model_name='noteprimaire',
            name='retenue',
            field=models.BooleanField(default=False, verbose_name='Note retenue pour la moyenne'),
        ),
    ]
