# Generated by Django 5.2.7 on 2025-10-29 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0105_evaluation_matiere_note_matiere'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listepresence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='listepresence',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listes_presences', to='school_admin.matiere', verbose_name='Matière'),
        ),
        migrations.AlterUniqueTogether(
            name='listepresence',
            unique_together={('classe', 'date', 'matiere')},
        ),
    ]
