# Generated by Django 5.2.6 on 2025-10-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0106_add_matiere_to_liste_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='moyenne',
            name='soumis',
            field=models.BooleanField(default=False, help_text='Indique si la moyenne est incluse dans un relevé officiellement soumis', verbose_name='Soumis'),
        ),
    ]
