# Generated by Django 5.2.7 on 2025-10-30 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0107_moyenne_soumis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(help_text='Objet de la convocation', max_length=200, verbose_name='Objet')),
                ('motif', models.TextField(help_text='Motif détaillé de la convocation', verbose_name='Motif')),
                ('date_convocation', models.DateField(help_text='Date du rendez-vous', verbose_name='Date de convocation')),
                ('heure_convocation', models.TimeField(help_text='Heure du rendez-vous', verbose_name='Heure de convocation')),
                ('lieu', models.CharField(default='Bureau du Directeur', help_text='Lieu du rendez-vous', max_length=200, verbose_name='Lieu')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de la convocation', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('vue', 'Vue par le parent'), ('honoree', 'Honorée'), ('non_honoree', 'Non honorée')], default='en_attente', help_text='Statut de la convocation', max_length=20, verbose_name='Statut')),
                ('actif', models.BooleanField(default=True, help_text='Convocation active ou archivée', verbose_name='Actif')),
                ('eleve', models.ForeignKey(help_text='Élève concerné par la convocation', on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='school_admin.eleve', verbose_name='Élève')),
                ('etablissement', models.ForeignKey(help_text='Établissement émetteur de la convocation', on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Convocation',
                'verbose_name_plural': 'Convocations',
                'ordering': ['-date_convocation', '-heure_convocation'],
                'indexes': [models.Index(fields=['eleve', 'date_convocation'], name='school_admi_eleve_i_f7c685_idx'), models.Index(fields=['etablissement', 'date_convocation'], name='school_admi_etablis_5f5e92_idx'), models.Index(fields=['statut'], name='school_admi_statut_9daa78_idx')],
            },
        ),
    ]
