# Generated by Django 5.2.7 on 2025-10-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0108_convocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocation',
            name='convocation_classe',
            field=models.BooleanField(default=False, help_text='Indique si cette convocation concerne toute une classe', verbose_name='Convocation de classe'),
        ),
    ]
