# Generated by Django 5.2.7 on 2025-10-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0109_convocation_convocation_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeliaisonparent',
            name='classe_eleve',
            field=models.CharField(blank=True, help_text='Classe fournie par le parent pour vérification', max_length=100, null=True, verbose_name="Classe de l'élève"),
        ),
        migrations.AddField(
            model_name='demandeliaisonparent',
            name='nom_parent_inscripteur',
            field=models.CharField(blank=True, help_text="Nom ou prénom du parent qui a inscrit l'enfant", max_length=200, null=True, verbose_name='Nom du parent inscripteur'),
        ),
        migrations.AddField(
            model_name='demandeliaisonparent',
            name='nombre_tentatives',
            field=models.PositiveIntegerField(default=1, help_text='Compteur de tentatives de liaison pour ce parent/élève', verbose_name='Nombre de tentatives'),
        ),
        migrations.AddField(
            model_name='demandeliaisonparent',
            name='raison_echec',
            field=models.TextField(blank=True, help_text='Détails sur pourquoi la liaison a échoué', null=True, verbose_name="Raison de l'échec"),
        ),
        migrations.AlterField(
            model_name='demandeliaisonparent',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée'), ('reussie', 'Réussie (liaison automatique)'), ('echec', 'Échec (vérification échouée)'), ('bloquee', 'Bloquée (trop de tentatives)')], default='en_attente', max_length=15, verbose_name='Statut de la demande'),
        ),
    ]
