# Generated by Django 5.2.7 on 2025-11-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0110_demandeliaisonparent_classe_eleve_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listepresence',
            options={'ordering': ['-date', '-numero_appel', 'classe__nom'], 'verbose_name': 'Liste de présence', 'verbose_name_plural': 'Listes de présence'},
        ),
        migrations.AlterUniqueTogether(
            name='listepresence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='listepresence',
            name='numero_appel',
            field=models.IntegerField(default=1, help_text="Numéro de l'appel du jour (1, 2 ou 3)", verbose_name="Numéro d'appel"),
        ),
        migrations.AlterUniqueTogether(
            name='listepresence',
            unique_together={('classe', 'date', 'matiere', 'numero_appel')},
        ),
    ]
