# Generated by Django 5.2.7 on 2025-11-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0111_add_numero_appel_to_listepresence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presence',
            options={'ordering': ['-date', '-numero_appel', 'eleve__nom', 'eleve__prenom'], 'verbose_name': 'Présence', 'verbose_name_plural': 'Présences'},
        ),
        migrations.RemoveIndex(
            model_name='presence',
            name='school_admi_date_b741f3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='presence',
            name='numero_appel',
            field=models.IntegerField(default=1, help_text="Numéro de l'appel du jour (1, 2 ou 3)", verbose_name="Numéro d'appel"),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('eleve', 'classe', 'date', 'numero_appel')},
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['date', 'classe', 'numero_appel'], name='school_admi_date_40fcc5_idx'),
        ),
    ]
