# Generated by Django 5.2.7 on 2025-11-01 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0112_add_numero_appel_to_presence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='presence',
            name='matiere',
            field=models.ForeignKey(blank=True, help_text='Matière concernée (uniquement pour lycée/collège)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='school_admin.matiere', verbose_name='Matière'),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('eleve', 'classe', 'date', 'numero_appel', 'matiere')},
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['classe', 'matiere', 'date'], name='school_admi_classe__de9f89_idx'),
        ),
    ]
