# Generated by Django 5.2.7 on 2025-11-05 00:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0113_alter_presence_unique_together_presence_matiere_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name="Titre de l'annonce")),
                ('contenu', models.TextField(verbose_name="Contenu de l'annonce")),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('destinataires', models.CharField(choices=[('tous', 'Tous'), ('enseignants', 'Enseignants'), ('parents', 'Parents'), ('eleves', 'Élèves'), ('personnel_administratif', 'Personnel Administratif'), ('enseignants_parents', 'Enseignants et Parents'), ('eleves_parents', 'Élèves et Parents')], default='tous', max_length=50, verbose_name='Destinataires')),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='annonces/fichiers/%Y/%m/', verbose_name='Fichier joint')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publiee', 'Publiée'), ('archivee', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('auteur_directeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_creees', to='school_admin.etablissement', verbose_name='Auteur (Directeur)')),
                ('auteur_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_creees', to='school_admin.personneladministratif', verbose_name='Auteur (Personnel)')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-date_publication', '-date_creation'],
                'indexes': [models.Index(fields=['-date_publication'], name='school_admi_date_pu_d10d7e_idx'), models.Index(fields=['etablissement', 'statut'], name='school_admi_etablis_20d8b6_idx')],
            },
        ),
    ]
