# Generated by Django 5.2.7 on 2025-11-05 00:32

from django.db import migrations, models
import json


def convert_destinataires_to_list(apps, schema_editor):
    """Convertir les anciennes valeurs de destinataires (string) en liste"""
    Annonce = apps.get_model('school_admin', 'Annonce')
    for annonce in Annonce.objects.all():
        # Récupérer la valeur actuelle
        old_value = annonce.destinataires_old
        if old_value:
            # Convertir en liste JSON
            annonce.destinataires = json.dumps([old_value])
        else:
            annonce.destinataires = json.dumps(['tous'])
        annonce.save(update_fields=['destinataires'])


def reverse_destinataires_to_string(apps, schema_editor):
    """Reconvertir les listes en chaînes (pour la migration inverse)"""
    Annonce = apps.get_model('school_admin', 'Annonce')
    for annonce in Annonce.objects.all():
        # Récupérer la valeur JSON
        if annonce.destinataires:
            try:
                dest_list = json.loads(annonce.destinataires)
                if dest_list and len(dest_list) > 0:
                    annonce.destinataires_old = dest_list[0]
                else:
                    annonce.destinataires_old = 'tous'
            except:
                annonce.destinataires_old = 'tous'
        else:
            annonce.destinataires_old = 'tous'
        annonce.save(update_fields=['destinataires_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0114_annonce'),
    ]

    operations = [
        # 1. Renommer l'ancien champ
        migrations.RenameField(
            model_name='annonce',
            old_name='destinataires',
            new_name='destinataires_old',
        ),
        # 2. Créer le nouveau champ JSONField
        migrations.AddField(
            model_name='annonce',
            name='destinataires',
            field=models.JSONField(default=list, verbose_name='Destinataires'),
        ),
        # 3. Convertir les données
        migrations.RunPython(convert_destinataires_to_list, reverse_destinataires_to_string),
        # 4. Supprimer l'ancien champ
        migrations.RemoveField(
            model_name='annonce',
            name='destinataires_old',
        ),
    ]

