# Generated by Django 5.2.6 on 2025-11-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0117_ponderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponderation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
