# Generated by Django 5.2.6 on 2025-11-07 14:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0119_update_ponderation_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoyennePeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_classe', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Moyenne de contrôle continu')),
                ('note_examen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name="Note d'examen")),
                ('moyenne_matiere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Moyenne de la matière (calculée selon pondération)')),
                ('coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Coefficient de la matière')),
                ('total_matiere', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total matière (moyenne_matiere × coefficient)')),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Moyenne générale de la période')),
                ('rang', models.PositiveIntegerField(blank=True, null=True, verbose_name="Rang de l'élève dans la classe")),
                ('appreciation_matiere', models.TextField(blank=True, null=True, verbose_name='Appréciation de la matière')),
                ('appreciation_generale', models.CharField(blank=True, max_length=255, null=True, verbose_name='Appréciation générale')),
                ('decision_conseil', models.CharField(blank=True, max_length=255, null=True, verbose_name='Décision du conseil')),
                ('poids_classe', models.PositiveSmallIntegerField(default=50, help_text='Pourcentage utilisé pour le calcul', verbose_name='Poids contrôle continu (%)')),
                ('poids_examen', models.PositiveSmallIntegerField(default=50, help_text='Pourcentage utilisé pour le calcul', verbose_name='Poids examen (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date du calcul')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('est_moyenne_generale', models.BooleanField(default=False, help_text='True si cette ligne représente la moyenne générale (sans matière)', verbose_name='Est moyenne générale')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_periodes', to='school_admin.eleve', verbose_name='Élève')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_periodes', to='school_admin.etablissement', verbose_name='Établissement')),
                ('matiere', models.ForeignKey(blank=True, help_text='Null pour la ligne de moyenne générale', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_periodes', to='school_admin.matiere', verbose_name='Matière')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_periodes', to='school_admin.periodescolaire', verbose_name='Période scolaire')),
            ],
            options={
                'verbose_name': 'Moyenne de période',
                'verbose_name_plural': 'Moyennes de période',
                'ordering': ['periode', 'eleve', '-est_moyenne_generale', 'matiere'],
                'indexes': [models.Index(fields=['eleve', 'periode'], name='school_admi_eleve_i_b6cc72_idx'), models.Index(fields=['etablissement', 'periode'], name='school_admi_etablis_80f75f_idx')],
                'unique_together': {('eleve', 'etablissement', 'periode', 'matiere', 'est_moyenne_generale')},
            },
        ),
    ]
