# Generated by Django 5.2.7 on 2025-11-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0120_add_moyenne_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='moyenneperiode',
            name='date_publication',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de publication'),
        ),
        migrations.AddField(
            model_name='moyenneperiode',
            name='est_publie',
            field=models.BooleanField(default=False, verbose_name='Bulletin publié'),
        ),
    ]
