# Generated by Django 5.2.6 on 2025-11-07 16:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('school_admin', '0121_moyenneperiode_date_publication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=180, verbose_name='Titre de la notification')),
                ('message', models.TextField(verbose_name='Contenu de la notification')),
                ('type_notification', models.CharField(choices=[('presence', 'Présence / Absence'), ('note', 'Note individuelle'), ('moyenne', 'Moyenne de période'), ('bulletin', 'Bulletin disponible'), ('sanction', 'Sanction appliquée'), ('information', 'Information générale')], max_length=20, verbose_name="Type d'évènement")),
                ('statut', models.CharField(choices=[('non_lu', 'Non lu'), ('lu', 'Lu'), ('archive', 'Archivé')], default='non_lu', max_length=10, verbose_name='Statut')),
                ('date_evenement', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de l'évènement")),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('donnees', models.JSONField(blank=True, default=dict, verbose_name='Données supplémentaires')),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Identifiant source')),
                ('notification_push_envoyee', models.BooleanField(default=False, verbose_name='Notification push envoyée')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_parents', to='school_admin.eleve', verbose_name='Élève')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='school_admin.parent', verbose_name='Parent')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_parents', to='contenttypes.contenttype', verbose_name='Type de contenu source')),
            ],
            options={
                'verbose_name': 'Notification parent',
                'verbose_name_plural': 'Notifications parents',
                'db_table': 'notifications_parents',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['parent', 'statut'], name='notificatio_parent__ad4dbc_idx'), models.Index(fields=['eleve', 'type_notification'], name='notificatio_eleve_i_573ffb_idx'), models.Index(fields=['date_creation'], name='notificatio_date_cr_0b279f_idx')],
            },
        ),
    ]
