# Generated by Django 5.2.6 on 2025-11-07 19:01

import uuid

from django.db import migrations, models


def populate_qr_identifiers(apps, schema_editor):
    Eleve = apps.get_model('school_admin', 'Eleve')
    for eleve in Eleve.objects.all():
        if not eleve.qr_code_identifier:
            eleve.qr_code_identifier = uuid.uuid4().hex
            eleve.save(update_fields=['qr_code_identifier'])


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0122_notificationparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='qr_code_data',
            field=models.TextField(blank=True, help_text="Charge utile encodée dans le QR code de l'élève", null=True, verbose_name='Données QR code'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='qr_code_generated_at',
            field=models.DateTimeField(blank=True, help_text='Dernière date de génération du QR code', null=True, verbose_name='Date de génération du QR code'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='qr_code_identifier',
            field=models.CharField(blank=True, editable=False, help_text="Identifiant unique du QR code de l'élève", max_length=64, null=True, unique=True, verbose_name='Identifiant QR code'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text="Image PNG générée pour le QR code de l'élève", null=True, upload_to='eleves/qrcodes/', verbose_name='Image du QR code'),
        ),
        migrations.RunPython(populate_qr_identifiers, migrations.RunPython.noop),
    ]
