# Generated by Django 5.2.6 on 2025-11-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0123_eleve_photo_profil_eleve_qr_code_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='logo',
            field=models.ImageField(blank=True, help_text="Image utilisée comme logo officiel de l'établissement", null=True, upload_to='etablissements/logos/', verbose_name="Logo de l'établissement"),
        ),
    ]
