# Generated by Django 5.2.6 on 2025-11-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0124_eleve_photo_profil_etablissement_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploidutemps',
            name='date_publication',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de publication'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='statut_publication',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20, verbose_name='Statut de publication'),
        ),
    ]
