# Generated by Django 5.2.6 on 2025-11-08 17:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('school_admin', '0125_eleve_photo_profil_emploidutemps_date_publication_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='eleve',
                    name='photo_profil',
                    field=models.ImageField(
                        upload_to='eleves/photos/',
                        blank=True,
                        null=True,
                        verbose_name='Photo de profil',
                        help_text="Photographie récente de l'élève pour son dossier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDirecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=180, verbose_name='Titre de la notification')),
                ('message', models.TextField(verbose_name='Contenu de la notification')),
                ('type_notification', models.CharField(choices=[('releve', 'Relevé de notes soumis'), ('sanction', 'Sanction disciplinaire'), ('information', 'Information générale')], default='information', max_length=20, verbose_name="Type d'évènement")),
                ('statut', models.CharField(choices=[('non_lu', 'Non lu'), ('lu', 'Lu'), ('archive', 'Archivé')], default='non_lu', max_length=10, verbose_name='Statut')),
                ('date_evenement', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de l'évènement")),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('donnees', models.JSONField(blank=True, default=dict, verbose_name='Données supplémentaires')),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Identifiant source')),
                ('notification_push_envoyee', models.BooleanField(default=False, verbose_name='Notification push envoyée')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_directeur', to='school_admin.etablissement', verbose_name='Établissement')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_directeur', to='contenttypes.contenttype', verbose_name='Type de contenu source')),
            ],
            options={
                'verbose_name': 'Notification directeur',
                'verbose_name_plural': 'Notifications directeur',
                'db_table': 'notifications_directeur',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['etablissement', 'statut'], name='notificatio_etablis_38c1dc_idx'), models.Index(fields=['type_notification'], name='notificatio_type_no_b871ba_idx'), models.Index(fields=['date_creation'], name='notificatio_date_cr_a53a29_idx')],
            },
        ),
    ]
