# Generated by Django 5.2.7 on 2025-11-12 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0131_appreciationconseilstandard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationeleve',
            name='type_notification',
            field=models.CharField(choices=[('annonce', 'Annonce'), ('bulletin', 'Bulletin'), ('note', 'Note'), ('sanction', 'Sanction'), ('evaluation', 'Évaluation programmée'), ('information', 'Information')], default='information', max_length=20, verbose_name="Type d'évènement"),
        ),
        migrations.AlterField(
            model_name='notificationparent',
            name='type_notification',
            field=models.CharField(choices=[('presence', 'Présence / Absence'), ('note', 'Note individuelle'), ('moyenne', 'Moyenne de période'), ('bulletin', 'Bulletin disponible'), ('sanction', 'Sanction appliquée'), ('evaluation', 'Évaluation programmée'), ('information', 'Information générale')], max_length=20, verbose_name="Type d'évènement"),
        ),
        migrations.CreateModel(
            name='ExerciceMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name="Titre de l'exercice")),
                ('description', models.TextField(blank=True, verbose_name='Description / Consignes')),
                ('date_rendu', models.DateField(help_text="Date à laquelle l'exercice doit être rendu", verbose_name='Date de rendu')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices_maison', to='school_admin.classe', verbose_name='Classe')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices_maison', to='school_admin.etablissement', verbose_name='Établissement')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices_maison', to='school_admin.matiere', verbose_name='Matière')),
                ('periode_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices_maison', to='school_admin.periodescolaire', verbose_name='Période scolaire')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices_maison', to='school_admin.professeur', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Exercice de maison',
                'verbose_name_plural': 'Exercices de maison',
                'ordering': ['-date_rendu', '-date_creation'],
                'indexes': [models.Index(fields=['classe', 'matiere'], name='school_admi_classe__6b6fda_idx'), models.Index(fields=['professeur', 'date_rendu'], name='school_admi_profess_59f775_idx')],
            },
        ),
    ]
