# Generated by Django 5.2.7 on 2025-11-13 01:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0132_alter_notificationeleve_type_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancienne_note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valeur initiale')),
                ('nouvelle_note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valeur proposée')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif de la justification')),
                ('description', models.TextField(blank=True, verbose_name='Détails complémentaires')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('commentaire_direction', models.TextField(blank=True, verbose_name='Commentaire de la direction')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation / refus')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications_notes', to='school_admin.classe', verbose_name='Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications_notes', to='school_admin.eleve', verbose_name='Élève')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications_notes', to='school_admin.etablissement', verbose_name='Établissement')),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications_notes', to='school_admin.evaluation', verbose_name='Évaluation (secondaire)')),
                ('evaluation_primaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications_notes', to='school_admin.evaluationprimaire', verbose_name='Évaluation (primaire)')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications_notes', to='school_admin.matiere', verbose_name='Matière')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='justifications', to='school_admin.note', verbose_name='Note (collège / lycée)')),
                ('note_primaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='justifications', to='school_admin.noteprimaire', verbose_name='Note (primaire)')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications_notes', to='school_admin.professeur', verbose_name='Professeur demandeur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications_notes_validees', to='school_admin.etablissement', verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Justification de note',
                'verbose_name_plural': 'Justifications de notes',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['statut'], name='school_admi_statut_df7772_idx'), models.Index(fields=['classe', 'statut'], name='school_admi_classe__7c53ff_idx'), models.Index(fields=['professeur', 'statut'], name='school_admi_profess_9f6e6d_idx')],
            },
        ),
    ]
