# Generated by Django 5.2.7 on 2025-11-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0133_justificationnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='moyennematiereprimaire',
            name='evaluations_utilisees',
            field=models.JSONField(blank=True, default=list, verbose_name='Identifiants des évaluations utilisées'),
        ),
        migrations.AddField(
            model_name='moyennematiereprimaire',
            name='mode_calcul',
            field=models.CharField(default='toutes', max_length=20, verbose_name='Mode de calcul utilisé'),
        ),
    ]
