# Generated by Django 5.2.7 on 2025-11-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0134_moyennematiereprimaire_evaluations_utilisees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moyennematiereprimaire',
            name='ponderation',
            field=models.CharField(default='50_50', max_length=10, verbose_name='Pondération devoirs/examen'),
        ),
    ]
