# Generated by Django 5.2.7 on 2025-11-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0135_moyennematiereprimaire_ponderation'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE school_admin_noteexamen
                        ADD COLUMN IF NOT EXISTS date_publication timestamp with time zone;
                    """,
                    reverse_sql="""
                        ALTER TABLE school_admin_noteexamen
                        DROP COLUMN IF EXISTS date_publication;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='noteexamen',
                    name='date_publication',
                    field=models.DateTimeField(blank=True, null=True, verbose_name='Date de publication'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE school_admin_noteexamen
                        ADD COLUMN IF NOT EXISTS note_publiee numeric(5, 2);
                    """,
                    reverse_sql="""
                        ALTER TABLE school_admin_noteexamen
                        DROP COLUMN IF EXISTS note_publiee;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='noteexamen',
                    name='note_publiee',
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Dernière note publiée'),
                ),
            ],
        ),
        migrations.AddField(
            model_name='noteexamen',
            name='statut_publication',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publiee', 'Publiée'), ('modifiee', 'Modifiée')], default='brouillon', max_length=20, verbose_name='Statut de publication'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE school_admin_noteprimaire
                        ADD COLUMN IF NOT EXISTS date_publication timestamp with time zone;
                    """,
                    reverse_sql="""
                        ALTER TABLE school_admin_noteprimaire
                        DROP COLUMN IF EXISTS date_publication;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='noteprimaire',
                    name='date_publication',
                    field=models.DateTimeField(blank=True, null=True, verbose_name='Date de publication'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE school_admin_noteprimaire
                        ADD COLUMN IF NOT EXISTS note_publiee numeric(5, 2);
                    """,
                    reverse_sql="""
                        ALTER TABLE school_admin_noteprimaire
                        DROP COLUMN IF EXISTS note_publiee;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='noteprimaire',
                    name='note_publiee',
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Dernière note publiée'),
                ),
            ],
        ),
        migrations.AddField(
            model_name='noteprimaire',
            name='statut_publication',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publiee', 'Publiée'), ('modifiee', 'Modifiée')], default='brouillon', max_length=20, verbose_name='Statut de publication'),
        ),
    ]
