# Generated by Django 5.2.7 on 2025-11-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0136_noteexamen_date_publication_noteexamen_note_publiee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_publication',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de publication'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_publiee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Dernière note publiée'),
        ),
        migrations.AddField(
            model_name='note',
            name='statut_publication',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publiee', 'Publiée'), ('modifiee', 'Modifiée')], default='brouillon', max_length=20, verbose_name='Statut de publication'),
        ),
    ]
