# Generated by Django 5.2.6 on 2025-11-15 00:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0138_moyenneperiode_security_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesseurOtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=6)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='school_admin.professeur')),
            ],
            options={
                'verbose_name': 'Code OTP Professeur',
                'verbose_name_plural': 'Codes OTP Professeurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
