# Generated by Django 5.2.6 on 2025-11-15 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0139_professeurotpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeurotpcode',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='school_admin.professeur'),
        ),
    ]
