# Generated by Django 5.2.7 on 2025-11-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0142_add_photo_profil_to_eleve'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='statut_reglementation',
            field=models.CharField(choices=[('hors_service', 'Hors service'), ('en_regle', 'En règle'), ('en_retard', 'En retard'), ('non_en_regle', 'Non en règle'), ('contentieux', 'Contentieux')], default='hors_service', max_length=20, verbose_name='Statut de réglementation'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='email',
            field=models.EmailField(blank=True, help_text='Ce champ est facultatif', max_length=254, null=True, unique=True, verbose_name='Adresse email'),
        ),
    ]
