# Generated by Django 5.2.7 on 2025-11-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0143_etablissement_statut_reglementation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturation',
            name='periode_facture',
            field=models.CharField(blank=True, help_text='Mois (ex: Janvier 2025) pour facturation mensuelle, Année (ex: 2025) pour facturation annuelle', max_length=50, null=True, verbose_name='Période de facturation'),
        ),
    ]
