# Generated by Django 5.2.7 on 2025-11-19 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0144_facturation_periode_facture'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du rapport')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type_rapport', models.CharField(choices=[('complet', 'Rapport complet'), ('resume', 'Résumé exécutif'), ('financier', 'Rapport financier uniquement'), ('operational', 'Rapport opérationnel')], default='complet', max_length=20, verbose_name='Type de rapport')),
                ('mois', models.IntegerField(help_text='Mois du rapport (1-12)', verbose_name='Mois')),
                ('annee', models.IntegerField(help_text='Année du rapport', verbose_name='Année')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours de génération'), ('genere', 'Généré'), ('erreur', 'Erreur')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('frequence', models.CharField(choices=[('manuel', 'Manuel'), ('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], default='manuel', max_length=20, verbose_name='Fréquence de génération')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='rapports_mensuels/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Fichier PDF')),
                ('taille_fichier', models.BigIntegerField(blank=True, null=True, verbose_name='Taille du fichier (octets)')),
                ('inclure_resume_executif', models.BooleanField(default=True, verbose_name='Inclure résumé exécutif')),
                ('inclure_donnees_financieres', models.BooleanField(default=True, verbose_name='Inclure données financières')),
                ('inclure_analyse_etablissements', models.BooleanField(default=True, verbose_name='Inclure analyse des établissements')),
                ('inclure_graphiques', models.BooleanField(default=True, verbose_name='Inclure graphiques et tableaux')),
                ('inclure_recommandations', models.BooleanField(default=True, verbose_name='Inclure recommandations')),
                ('donnees_rapport', models.JSONField(blank=True, default=dict, verbose_name='Données du rapport')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_generation', models.DateTimeField(blank=True, null=True, verbose_name='Date de génération')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('temps_generation', models.FloatField(blank=True, null=True, verbose_name='Temps de génération (secondes)')),
            ],
            options={
                'verbose_name': 'Rapport mensuel',
                'verbose_name_plural': 'Rapports mensuels',
                'db_table': 'rapports_mensuels',
                'ordering': ['-annee', '-mois', '-date_creation'],
                'indexes': [models.Index(fields=['annee', 'mois'], name='rapports_me_annee_512c4f_idx'), models.Index(fields=['statut'], name='rapports_me_statut_92676e_idx'), models.Index(fields=['type_rapport'], name='rapports_me_type_ra_9913d1_idx'), models.Index(fields=['date_creation'], name='rapports_me_date_cr_eb28fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('mois', 'annee', 'type_rapport'), name='unique_rapport_periode_type')],
            },
        ),
    ]
