# Generated by Django 5.2.7 on 2025-11-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0145_rapportmensuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteuser',
            name='salaire',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salaire mensuel en FCFA', max_digits=10, null=True, verbose_name='Salaire'),
        ),
    ]
