# Generated by Django 5.2.7 on 2025-11-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0146_add_salaire_to_compteuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='date_paiement',
            field=models.DateField(blank=True, help_text='Date à laquelle la dépense a été payée', null=True, verbose_name='Date de paiement'),
        ),
        migrations.AddField(
            model_name='depense',
            name='methode_paiement',
            field=models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('autre', 'Autre')], default='virement', help_text='Méthode utilisée pour le paiement', max_length=50, verbose_name='Méthode de paiement'),
        ),
        migrations.AddField(
            model_name='depense',
            name='numero_facture',
            field=models.CharField(blank=True, help_text='Numéro de facture ou référence', max_length=100, null=True, verbose_name='Numéro de facture'),
        ),
    ]
