# Generated by Django 5.2.7 on 2025-11-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0147_depense_date_paiement_depense_methode_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='type_depense',
            field=models.CharField(choices=[('unique', 'Paiement unique'), ('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('semestrielle', 'Semestrielle'), ('annuelle', 'Annuelle'), ('autre', 'Autre fréquence')], default='unique', help_text='Indique si la dépense est ponctuelle ou récurrente', max_length=20, verbose_name='Type de dépense'),
        ),
    ]
