# Generated by Django 5.2.7 on 2025-11-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0152_eleve_password_reset_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code de réinitialisation'),
        ),
        migrations.AddField(
            model_name='parent',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration du code de réinitialisation'),
        ),
    ]
