# Generated by Django 5.2.7 on 2025-11-21 07:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0153_parent_password_reset_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospection',
            name='statut_etablissement',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('contacte', 'Contacté'), ('rendez_vous', 'Rendez-vous'), ('non_interesse', 'Non intéressé'), ('interesse', 'Intéressé'), ('negociation', 'En négociation'), ('devis_envoye', 'Devis envoyé'), ('contrat_signe', 'Contrat signé')], max_length=255, verbose_name="Statut d'établissement"),
        ),
        migrations.CreateModel(
            name='SoumissionListePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions_listes_presences', to='school_admin.classe', verbose_name='Classe')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions_listes_presences', to='school_admin.etablissement', verbose_name='Établissement')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soumissions_listes_presences', to='school_admin.matiere', verbose_name='Matière')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions_listes_presences', to='school_admin.professeur', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Soumission de liste de présence',
                'verbose_name_plural': 'Soumissions de listes de présence',
                'ordering': ['-date', '-date_soumission', 'classe__nom'],
                'indexes': [models.Index(fields=['classe', 'matiere', 'date'], name='school_admi_classe__17a902_idx'), models.Index(fields=['professeur', 'date'], name='school_admi_profess_d6c49c_idx'), models.Index(fields=['etablissement', 'date'], name='school_admi_etablis_77568a_idx')],
                'unique_together': {('classe', 'professeur', 'matiere', 'date')},
            },
        ),
    ]
