# Generated by Django 5.2.7 on 2025-11-21 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0155_remove_type_evaluation_and_duree_from_evaluations'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoefficientMatiereGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_groupe', models.CharField(help_text="Ex: '6eme', '5eme', 'Premiere L', etc.", max_length=100, verbose_name='Nom du groupe de classes')),
                ('coefficient', models.DecimalField(decimal_places=1, default=1.0, help_text='Coefficient de la matière pour ce groupe de classes', max_digits=3, verbose_name='Coefficient')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients_matiere_groupe', to='school_admin.etablissement', verbose_name='Établissement')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients_par_groupe', to='school_admin.matiere', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Coefficient Matière par Groupe',
                'verbose_name_plural': 'Coefficients Matière par Groupe',
                'ordering': ['matiere', 'nom_groupe'],
                'indexes': [models.Index(fields=['matiere', 'etablissement'], name='school_admi_matiere_290290_idx'), models.Index(fields=['nom_groupe'], name='school_admi_nom_gro_d08282_idx')],
                'unique_together': {('matiere', 'etablissement', 'nom_groupe')},
            },
        ),
    ]
