# Generated by Django 5.2.7 on 2025-11-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0156_add_coefficient_matiere_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='type_etablissement',
            field=models.CharField(choices=[('primary', 'École Primaire'), ('collège', 'Collège'), ('lycée', 'Lycée'), ('collège_lycée', 'Collège + Lycée'), ('mixte', 'Établissement Mixte')], max_length=20, verbose_name="Type d'établissement"),
        ),
    ]
