# Generated by Django 5.2.7 on 2025-11-24 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0157_add_etablissement_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Format: 2025-2026', max_length=20, verbose_name='Libellé')),
                ('annee_debut', models.IntegerField(help_text='Année de début (ex: 2025)', verbose_name='Année de début')),
                ('annee_fin', models.IntegerField(help_text='Année de fin (ex: 2026)', verbose_name='Année de fin')),
                ('date_debut', models.DateField(help_text="Date de début de l'année scolaire", verbose_name='Date de début')),
                ('date_fin', models.DateField(help_text="Date de fin de l'année scolaire", verbose_name='Date de fin')),
                ('est_active', models.BooleanField(default=False, help_text="Indique si cette année scolaire est la session active pour l'établissement", verbose_name='Session active')),
                ('est_ouverte', models.BooleanField(default=False, help_text='Indique si la session est ouverte (peut être créée avant le début)', verbose_name='Session ouverte')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annees_scolaires', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
                'ordering': ['-annee_debut', '-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='evaluation',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='moyenne',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moyennes', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='note',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='presence',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddIndex(
            model_name='anneescolaire',
            index=models.Index(fields=['etablissement', 'est_active'], name='school_admi_etablis_33f257_idx'),
        ),
        migrations.AddIndex(
            model_name='anneescolaire',
            index=models.Index(fields=['etablissement', 'date_debut', 'date_fin'], name='school_admi_etablis_ba0ab7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='anneescolaire',
            unique_together={('etablissement', 'libelle')},
        ),
    ]
