# Generated by Django 5.2.7 on 2025-11-24 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0158_add_annee_scolaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationprofesseur',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_professeurs', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='affectationprofesseurprimaire',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_professeurs_primaire', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='affectationsalle',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_salles', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_annee_scolaire', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
    ]
