# Generated by Django 5.2.7 on 2025-11-24 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0160_configurationhoraire_annee_scolaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploidutemps',
            name='annee_scolaire_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_du_temps', to='school_admin.anneescolaire', verbose_name='Année scolaire (référence)'),
        ),
        migrations.AddField(
            model_name='evaluationprimaire',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_primaire', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='exercicemaison',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices_maison_annee_scolaire', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='justificationnote',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications_notes_annee_scolaire', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='moyenneperiode',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moyennes_periodes_annee_scolaire', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
    ]
