# Generated by Django 5.2.7 on 2025-11-24 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0161_emploidutemps_annee_scolaire_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moyennematiereprimaire',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moyennes_matieres_primaire_annee_scolaire', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='noteexamen',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_examens_annee_scolaire', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='noteprimaire',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_primaire_annee_scolaire', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='notificationdirecteur',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_directeur', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='notificationeleve',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_eleves', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='notificationenseignant',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_enseignants', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='notificationparent',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_parents', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
    ]
