# Generated by Django 5.2.7 on 2025-11-24 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0162_moyennematiereprimaire_annee_scolaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodescolaire',
            name='annee_scolaire_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodes_scolaires_annee_scolaire', to='school_admin.anneescolaire', verbose_name='Année scolaire (référence)'),
        ),
        migrations.AddField(
            model_name='relevenotes',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releves_notes_annee_scolaire', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='sanction',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_annee_scolaire', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='sessionexamen',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_examens_annee_scolaire', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
    ]
