# Generated by Django 5.2.7 on 2025-11-24 08:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0163_periodescolaire_annee_scolaire_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de famille de l'élève", max_length=100, verbose_name='Nom de famille')),
                ('prenom', models.CharField(help_text="Prénom de l'élève", max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(help_text="Date de naissance de l'élève", verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(help_text="Lieu de naissance de l'élève", max_length=100, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], help_text="Sexe de l'élève", max_length=1, verbose_name='Sexe')),
                ('nationalite', models.CharField(help_text="Nationalité de l'élève", max_length=100, verbose_name='Nationalité')),
                ('adresse', models.TextField(blank=True, help_text="Adresse de résidence de l'élève (optionnel)", null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, help_text="Numéro de téléphone de l'élève", max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, help_text="Adresse email de l'élève", max_length=254, null=True, verbose_name='Email')),
                ('numero_eleve', models.CharField(help_text="Numéro unique d'identification de l'élève", max_length=20, verbose_name="Numéro d'élève")),
                ('matricule_eleve', models.CharField(blank=True, help_text="Matricule de connexion de l'élève (ex: BP2025001)", max_length=20, null=True, verbose_name='Matricule élève')),
                ('date_inscription', models.DateField(help_text="Date d'inscription de l'élève", verbose_name="Date d'inscription")),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle inscription'), ('transfert', "Transfert d'établissement"), ('reinscription', 'Réinscription')], help_text="Type d'inscription de l'élève", max_length=20, verbose_name="Statut d'inscription")),
                ('parent_nom', models.CharField(help_text='Nom de famille du parent ou tuteur', max_length=100, verbose_name='Nom du parent/tuteur')),
                ('parent_prenom', models.CharField(help_text='Prénom du parent ou tuteur', max_length=100, verbose_name='Prénom du parent/tuteur')),
                ('parent_telephone', models.CharField(help_text='Numéro de téléphone du parent ou tuteur', max_length=20, verbose_name='Téléphone du parent/tuteur')),
                ('parent_email', models.EmailField(blank=True, help_text='Adresse email du parent ou tuteur (optionnel)', max_length=254, null=True, verbose_name='Email du parent/tuteur')),
                ('parent_adresse', models.TextField(blank=True, help_text='Adresse complète du parent ou tuteur (optionnel)', null=True, verbose_name='Adresse du parent/tuteur')),
                ('parent_profession', models.CharField(blank=True, help_text='Profession du parent ou tuteur (optionnel)', max_length=100, null=True, verbose_name='Profession du parent/tuteur')),
                ('parent_lien', models.CharField(choices=[('pere', 'Père'), ('mere', 'Mère'), ('grand_parent', 'Grand-parent'), ('oncle_tante', 'Oncle/Tante'), ('frere_soeur', 'Frère/Sœur'), ('autre_famille', 'Autre membre de la famille'), ('tuteur_legal', 'Tuteur légal'), ('autre', 'Autre')], help_text="Lien de parenté du parent/tuteur avec l'élève", max_length=20, verbose_name="Lien avec l'élève")),
                ('document_acte_naissance', models.BooleanField(default=False, help_text='Acte de naissance fourni', verbose_name='Acte de naissance')),
                ('document_cni', models.BooleanField(default=False, help_text="Carte nationale d'identité fournie", verbose_name="Carte nationale d'identité")),
                ('document_passeport', models.BooleanField(default=False, help_text='Passeport fourni', verbose_name='Passeport')),
                ('document_bulletin_precedent', models.BooleanField(default=False, help_text="Bulletin de l'année précédente fourni", verbose_name="Bulletin de l'année précédente")),
                ('document_certificat_scolarite', models.BooleanField(default=False, help_text='Certificat de scolarité fourni', verbose_name='Certificat de scolarité')),
                ('document_livret_scolaire', models.BooleanField(default=False, help_text='Livret scolaire fourni', verbose_name='Livret scolaire')),
                ('document_certificat_medical', models.BooleanField(default=False, help_text='Certificat médical fourni', verbose_name='Certificat médical')),
                ('document_carnet_vaccination', models.BooleanField(default=False, help_text='Carnet de vaccination fourni', verbose_name='Carnet de vaccination')),
                ('document_assurance_maladie', models.BooleanField(default=False, help_text="Attestation d'assurance maladie fournie", verbose_name="Attestation d'assurance maladie")),
                ('document_justificatif_domicile', models.BooleanField(default=False, help_text='Justificatif de domicile fourni', verbose_name='Justificatif de domicile')),
                ('document_photo_identite', models.BooleanField(default=False, help_text="Photo d'identité fournie", verbose_name="Photo d'identité")),
                ('document_autorisation_parentale', models.BooleanField(default=False, help_text='Autorisation parentale fournie', verbose_name='Autorisation parentale')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement d'inscription", verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('annee_scolaire', models.ForeignKey(help_text="Année scolaire de l'inscription", on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_eleves', to='school_admin.anneescolaire', verbose_name='Année scolaire')),
                ('classe', models.ForeignKey(blank=True, help_text="Classe d'affectation de l'élève", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_eleves', to='school_admin.classe', verbose_name='Classe')),
                ('eleve', models.ForeignKey(blank=True, help_text="Référence à l'élève dans le système (peut être null si l'élève a été supprimé)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='school_admin.eleve', verbose_name='Élève')),
                ('etablissement', models.ForeignKey(help_text='Établissement de scolarisation', on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_eleves', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': "Inscription d'élève",
                'verbose_name_plural': "Inscriptions d'élèves",
                'ordering': ['-annee_scolaire', '-date_inscription', 'nom', 'prenom'],
                'indexes': [models.Index(fields=['annee_scolaire', 'etablissement'], name='school_admi_annee_s_927a34_idx'), models.Index(fields=['annee_scolaire', 'classe'], name='school_admi_annee_s_d13629_idx'), models.Index(fields=['matricule_eleve'], name='school_admi_matricu_9507b2_idx'), models.Index(fields=['date_inscription'], name='school_admi_date_in_4a9689_idx')],
                'unique_together': {('annee_scolaire', 'matricule_eleve')},
            },
        ),
        migrations.CreateModel(
            name='InscriptionParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, help_text='Adresse email du parent', max_length=254, null=True, verbose_name='Email')),
                ('matricule_parental', models.CharField(help_text='Identifiant unique du parent (ex: BPP2025001)', max_length=20, verbose_name='Matricule parental')),
                ('type_parent', models.CharField(choices=[('mere', 'Mère'), ('pere', 'Père'), ('tuteur', 'Tuteur/Tutrice')], max_length=10, verbose_name='Type de parent')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession')),
                ('date_inscription', models.DateField(help_text="Date d'inscription du parent", verbose_name="Date d'inscription")),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, help_text="Date de création de l'enregistrement d'inscription", verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('annee_scolaire', models.ForeignKey(help_text="Année scolaire de l'inscription", on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_parents', to='school_admin.anneescolaire', verbose_name='Année scolaire')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_parents', to='school_admin.etablissement', verbose_name='Établissement')),
                ('parent', models.ForeignKey(blank=True, help_text='Référence au parent dans le système (peut être null si le parent a été supprimé)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='school_admin.parent', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Inscription de parent',
                'verbose_name_plural': 'Inscriptions de parents',
                'ordering': ['-annee_scolaire', '-date_inscription', 'nom', 'prenom'],
                'indexes': [models.Index(fields=['annee_scolaire', 'etablissement'], name='school_admi_annee_s_fa382a_idx'), models.Index(fields=['matricule_parental'], name='school_admi_matricu_a7433e_idx'), models.Index(fields=['date_inscription'], name='school_admi_date_in_f6e265_idx')],
                'unique_together': {('annee_scolaire', 'matricule_parental')},
            },
        ),
    ]
