# Generated by Django 5.2.6 on 2025-11-24 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0164_inscriptioneleve_inscriptionparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardsreussite',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standards_reussite', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
    ]
