# Generated by Django 5.2.7 on 2025-11-25 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0165_standardsreussite_annee_scolaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='listepresence',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listes_presences', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
    ]
