# Generated by Django 5.2.7 on 2025-11-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('school_admin', '0166_add_annee_scolaire_to_liste_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationeleve',
            name='lu',
            field=models.BooleanField(default=False, help_text='Indique si la notification a été lue', verbose_name='Lu'),
        ),
        migrations.RunPython(
            # Migration de données : synchroniser lu avec statut
            lambda apps, schema_editor: apps.get_model('school_admin', 'NotificationEleve').objects.filter(statut='lu').update(lu=True),
            reverse_code=lambda apps, schema_editor: None,
        ),
        migrations.AddIndex(
            model_name='notificationeleve',
            index=models.Index(fields=['eleve', 'lu'], name='notificatio_eleve_i_028a1d_idx'),
        ),
    ]
