# Generated by Django 5.2.7 on 2025-11-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('school_admin', '0167_add_lu_field_to_notification_eleve'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationenseignant',
            name='lu',
            field=models.BooleanField(default=False, help_text='Indique si la notification a été lue', verbose_name='Lu'),
        ),
        migrations.AddField(
            model_name='notificationparent',
            name='lu',
            field=models.BooleanField(default=False, help_text='Indique si la notification a été lue', verbose_name='Lu'),
        ),
        migrations.RunPython(
            # Migration de données : synchroniser lu avec statut pour les enseignants
            lambda apps, schema_editor: apps.get_model('school_admin', 'NotificationEnseignant').objects.filter(statut='lu').update(lu=True),
            reverse_code=lambda apps, schema_editor: None,
        ),
        migrations.RunPython(
            # Migration de données : synchroniser lu avec statut pour les parents
            lambda apps, schema_editor: apps.get_model('school_admin', 'NotificationParent').objects.filter(statut='lu').update(lu=True),
            reverse_code=lambda apps, schema_editor: None,
        ),
        migrations.AddIndex(
            model_name='notificationenseignant',
            index=models.Index(fields=['enseignant', 'lu'], name='notificatio_enseign_107387_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationparent',
            index=models.Index(fields=['parent', 'lu'], name='notificatio_parent__1c920f_idx'),
        ),
    ]
