# Generated by Django 5.2.7 on 2025-11-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('school_admin', '0168_add_lu_field_to_notification_enseignant_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdirecteur',
            name='lu',
            field=models.BooleanField(default=False, help_text='Indique si la notification a été lue', verbose_name='Lu'),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('school_admin', 'NotificationDirecteur').objects.filter(statut='lu').update(lu=True),
            reverse_code=lambda apps, schema_editor: None,
        ),
        migrations.AddIndex(
            model_name='notificationdirecteur',
            index=models.Index(fields=['etablissement', 'lu'], name='notificatio_etablis_7c4d3b_idx'),
        ),
    ]
