# Generated by Django 5.2.7 on 2025-11-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0169_add_lu_field_to_notification_directeur'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affectationprofesseur',
            unique_together={('professeur', 'classe', 'matiere', 'annee_scolaire')},
        ),
        migrations.AlterUniqueTogether(
            name='affectationprofesseurprimaire',
            unique_together={('professeur', 'classe', 'annee_scolaire')},
        ),
        migrations.AddIndex(
            model_name='affectationprofesseur',
            index=models.Index(fields=['professeur', 'classe', 'matiere', 'annee_scolaire'], name='school_admi_profess_f7f90b_idx'),
        ),
        migrations.AddIndex(
            model_name='affectationprofesseur',
            index=models.Index(fields=['annee_scolaire', 'actif'], name='school_admi_annee_s_eab8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='affectationprofesseurprimaire',
            index=models.Index(fields=['professeur', 'classe', 'annee_scolaire'], name='school_admi_profess_7de3d6_idx'),
        ),
        migrations.AddIndex(
            model_name='affectationprofesseurprimaire',
            index=models.Index(fields=['annee_scolaire', 'actif'], name='school_admi_annee_s_8c38f4_idx'),
        ),
    ]
