# Generated by Django 5.2.7 on 2025-11-28 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0170_alter_affectation_unique_together_include_annee_scolaire'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='soumissionlistepresence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='soumissionlistepresence',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soumissions_listes_presences', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AlterUniqueTogether(
            name='soumissionlistepresence',
            unique_together={('classe', 'professeur', 'matiere', 'date', 'annee_scolaire')},
        ),
        migrations.AddIndex(
            model_name='soumissionlistepresence',
            index=models.Index(fields=['annee_scolaire', 'date'], name='school_admi_annee_s_5bdc50_idx'),
        ),
    ]
