# Generated by Django 5.2.7 on 2025-11-29 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0171_add_annee_scolaire_to_soumission_liste_presence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listepresence',
            unique_together={('classe', 'date', 'matiere', 'numero_appel', 'annee_scolaire')},
        ),
    ]
