# Generated by Django 5.2.7 on 2025-11-29 01:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0172_alter_listepresence_unique_together_include_annee_scolaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoyenneAnnuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_annuelle', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Moyenne annuelle')),
                ('nombre_periodes', models.PositiveIntegerField(default=0, help_text='Nombre de périodes dont les moyennes ont été additionnées', verbose_name='Nombre de périodes utilisées pour le calcul')),
                ('date_calcul', models.DateTimeField(auto_now_add=True, verbose_name='Date de calcul')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_annuelles', to='school_admin.anneescolaire', verbose_name='Année scolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_annuelles', to='school_admin.eleve', verbose_name='Élève')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_annuelles', to='school_admin.etablissement', verbose_name='Établissement')),
                ('periode_calcul', models.ForeignKey(help_text='La période à partir de laquelle la moyenne annuelle a été calculée', on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_annuelles_calculees', to='school_admin.periodescolaire', verbose_name='Période où le calcul a été effectué')),
            ],
            options={
                'verbose_name': 'Moyenne annuelle',
                'verbose_name_plural': 'Moyennes annuelles',
                'ordering': ['-date_calcul', 'eleve__nom', 'eleve__prenom'],
                'indexes': [models.Index(fields=['eleve', 'annee_scolaire', 'periode_calcul'], name='school_admi_eleve_i_377988_idx'), models.Index(fields=['etablissement', 'annee_scolaire'], name='school_admi_etablis_bef571_idx')],
                'unique_together': {('eleve', 'etablissement', 'annee_scolaire', 'periode_calcul')},
            },
        ),
    ]
