# Generated by Django 5.2.6 on 2025-11-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0175_ensure_moyenne_avec_coefficient_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardsreussite',
            name='appreciation_conseil',
        ),
        migrations.RemoveField(
            model_name='standardsreussite',
            name='moyenne_redoublement',
        ),
        migrations.AddField(
            model_name='eleve',
            name='conditions_acceptees',
            field=models.BooleanField(default=False, help_text="Indique si l'élève a accepté les conditions d'utilisation et la politique de confidentialité", verbose_name='Conditions acceptées'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='conditions_acceptees',
            field=models.BooleanField(default=False, help_text="Indique si l'établissement a accepté les conditions d'utilisation et la politique de confidentialité", verbose_name='Conditions acceptées'),
        ),
        migrations.AddField(
            model_name='parent',
            name='conditions_acceptees',
            field=models.BooleanField(default=False, help_text="Indique si le parent a accepté les conditions d'utilisation et la politique de confidentialité", verbose_name='Conditions acceptées'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='conditions_acceptees',
            field=models.BooleanField(default=False, help_text="Indique si le professeur a accepté les conditions d'utilisation et la politique de confidentialité", verbose_name='Conditions acceptées'),
        ),
    ]
