# Generated by Django 5.2.7 on 2025-12-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0176_remove_standardsreussite_appreciation_conseil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personneladministratif',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email professionnel'),
        ),
    ]
