# Generated by Django 5.2.7 on 2025-12-08 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0177_make_email_optional_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LienPreinscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, help_text='Token unique pour le lien de préinscription', max_length=64, unique=True, verbose_name='Token unique')),
                ('actif', models.BooleanField(default=True, help_text='Indique si le lien est actif et peut être utilisé', verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création du lien', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('nombre_utilisations', models.IntegerField(default=0, help_text='Nombre de fois que le lien a été utilisé', verbose_name="Nombre d'utilisations")),
                ('etablissement', models.OneToOneField(help_text='Établissement associé à ce lien', on_delete=django.db.models.deletion.CASCADE, related_name='lien_preinscription', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Lien de préinscription',
                'verbose_name_plural': 'Liens de préinscription',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PreinscriptionEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de famille de l'élève", max_length=100, verbose_name='Nom de famille')),
                ('prenom', models.CharField(help_text="Prénom de l'élève", max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(help_text="Date de naissance de l'élève", verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(help_text="Lieu de naissance de l'élève", max_length=100, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], help_text="Sexe de l'élève", max_length=1, verbose_name='Sexe')),
                ('nationalite', models.CharField(help_text="Nationalité de l'élève", max_length=100, verbose_name='Nationalité')),
                ('adresse', models.TextField(blank=True, help_text="Adresse de résidence de l'élève", null=True, verbose_name='Adresse')),
                ('statut_inscription', models.CharField(choices=[('nouvelle', 'Nouvelle inscription'), ('reinscription', 'Réinscription')], default='nouvelle', help_text="Type d'inscription", max_length=20, verbose_name="Type d'inscription")),
                ('parent_nom', models.CharField(help_text='Nom de famille du parent ou tuteur', max_length=100, verbose_name='Nom du parent/tuteur')),
                ('parent_prenom', models.CharField(help_text='Prénom du parent ou tuteur', max_length=100, verbose_name='Prénom du parent/tuteur')),
                ('parent_telephone', models.CharField(help_text='Numéro de téléphone du parent ou tuteur', max_length=20, verbose_name='Téléphone du parent/tuteur')),
                ('parent_adresse', models.TextField(blank=True, help_text='Adresse du parent ou tuteur', null=True, verbose_name='Adresse du parent/tuteur')),
                ('parent_profession', models.CharField(blank=True, help_text='Profession du parent ou tuteur', max_length=100, null=True, verbose_name='Profession du parent/tuteur')),
                ('parent_lien', models.CharField(choices=[('pere', 'Père'), ('mere', 'Mère'), ('grand_parent', 'Grand-parent'), ('oncle_tante', 'Oncle/Tante'), ('frere_soeur', 'Frère/Sœur'), ('autre_famille', 'Autre membre de la famille'), ('tuteur_legal', 'Tuteur légal'), ('autre', 'Autre')], help_text="Lien de parenté ou relation avec l'élève", max_length=50, verbose_name="Lien avec l'élève")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', help_text='Statut de la préinscription', max_length=20, verbose_name='Statut')),
                ('commentaires_parent', models.TextField(blank=True, help_text='Commentaires ou informations supplémentaires fournis par le parent', null=True, verbose_name='Commentaires du parent')),
                ('commentaires_etablissement', models.TextField(blank=True, help_text="Commentaires ou notes de l'établissement lors de la validation", null=True, verbose_name="Commentaires de l'établissement")),
                ('date_soumission', models.DateTimeField(auto_now_add=True, help_text='Date à laquelle la préinscription a été soumise', verbose_name='Date de soumission')),
                ('date_validation', models.DateTimeField(blank=True, help_text='Date à laquelle la préinscription a été validée ou rejetée', null=True, verbose_name='Date de validation')),
                ('classe_souhaitee', models.ForeignKey(blank=True, help_text="Classe souhaitée pour l'inscription", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preinscriptions', to='school_admin.classe', verbose_name='Classe souhaitée')),
                ('etablissement', models.ForeignKey(help_text='Établissement concerné', on_delete=django.db.models.deletion.CASCADE, related_name='preinscriptions_eleves', to='school_admin.etablissement', verbose_name='Établissement')),
                ('lien_preinscription', models.ForeignKey(help_text='Lien utilisé pour cette préinscription', on_delete=django.db.models.deletion.CASCADE, related_name='preinscriptions', to='school_admin.lienpreinscription', verbose_name='Lien de préinscription')),
                ('valide_par', models.ForeignKey(blank=True, help_text='Directeur ayant validé la préinscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preinscriptions_validees', to='school_admin.etablissement', verbose_name='Validé par')),
            ],
            options={
                'verbose_name': "Préinscription d'élève",
                'verbose_name_plural': "Préinscriptions d'élèves",
                'ordering': ['-date_soumission'],
            },
        ),
    ]
