# Generated by Django 5.2.7 on 2025-12-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0178_add_preinscription_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='qr_auth_token',
            field=models.CharField(blank=True, editable=False, help_text="Token unique pour l'authentification par QR Code", max_length=64, null=True, unique=True, verbose_name="Token d'authentification QR"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='qr_auth_token_generated_at',
            field=models.DateTimeField(blank=True, help_text="Date de génération du token d'authentification QR", null=True, verbose_name='Date de génération du token QR'),
        ),
        migrations.AddField(
            model_name='parent',
            name='qr_auth_token',
            field=models.CharField(blank=True, editable=False, help_text="Token unique pour l'authentification par QR Code", max_length=64, null=True, unique=True, verbose_name="Token d'authentification QR"),
        ),
        migrations.AddField(
            model_name='parent',
            name='qr_auth_token_generated_at',
            field=models.DateTimeField(blank=True, help_text="Date de génération du token d'authentification QR", null=True, verbose_name='Date de génération du token QR'),
        ),
    ]
