# Generated by Django 5.2.7 on 2025-12-10 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0179_add_qr_auth_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificationnote',
            name='note_examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='justifications', to='school_admin.noteexamen', verbose_name="Note d'examen"),
        ),
        migrations.AlterField(
            model_name='notificationdirecteur',
            name='type_notification',
            field=models.CharField(choices=[('releve', 'Relevé de notes soumis'), ('sanction', 'Sanction disciplinaire'), ('justification_note', 'Justification de note'), ('information', 'Information générale')], default='information', max_length=20, verbose_name="Type d'évènement"),
        ),
    ]
