# Generated by Django 5.2.7 on 2025-12-14 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0181_modifier_creneau_emploi_temps_horaires_obligatoires'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteIdentitePersonnalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays_nom', models.CharField(default='RÉPUBLIQUE DU SÉNÉGAL', help_text='Nom du pays à afficher (ex: RÉPUBLIQUE DU SÉNÉGAL)', max_length=255, verbose_name='Nom du pays')),
                ('devise_pays', models.CharField(default='UN PEUPLE - UN BUT - UNE FOI', help_text='Devise nationale à afficher (ex: UN PEUPLE - UN BUT - UNE FOI)', max_length=255, verbose_name='Devise du pays')),
                ('titre_carte', models.CharField(default="CARTE D'IDENTITÉ SCOLAIRE", help_text="Titre à afficher sur la carte (ex: CARTE D'IDENTITÉ SCOLAIRE)", max_length=255, verbose_name='Titre de la carte')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de la personnalisation', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('etablissement', models.OneToOneField(help_text='Établissement concerné par cette personnalisation', on_delete=django.db.models.deletion.CASCADE, related_name='carte_identite_personnalisation', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': "Personnalisation de carte d'identité",
                'verbose_name_plural': "Personnalisations de cartes d'identité",
                'ordering': ['-date_modification'],
            },
        ),
    ]
