# Generated by Django 5.2.7 on 2025-12-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0182_add_carte_identite_personnalisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteidentitepersonnalisation',
            name='devise_etablissement',
            field=models.CharField(default='Discipline - Travail - Réussite', help_text="Devise de l'établissement à afficher au verso de la carte (ex: Discipline - Travail - Réussite)", max_length=255, verbose_name="Devise de l'établissement"),
        ),
    ]
