# Generated by Django 5.2.7 on 2025-12-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0183_add_devise_etablissement_carte_identite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteidentitepersonnalisation',
            name='devise_etablissement',
            field=models.CharField(default='[DEVISE DE VOTRE ÉTABLISSEMENT]', help_text="Devise de l'établissement à afficher au verso de la carte (ex: Discipline - Travail - Réussite)", max_length=255, verbose_name="Devise de l'établissement"),
        ),
        migrations.AlterField(
            model_name='carteidentitepersonnalisation',
            name='devise_pays',
            field=models.CharField(default='[DEVISE NATIONALE]', help_text='Devise nationale à afficher (ex: UN PEUPLE - UN BUT - UNE FOI, Liberté - Égalité - Fraternité, etc.)', max_length=255, verbose_name='Devise du pays'),
        ),
        migrations.AlterField(
            model_name='carteidentitepersonnalisation',
            name='pays_nom',
            field=models.CharField(default='RÉPUBLIQUE DE [VOTRE PAYS]', help_text='Nom du pays à afficher (ex: RÉPUBLIQUE DU SÉNÉGAL, RÉPUBLIQUE FRANÇAISE, etc.)', max_length=255, verbose_name='Nom du pays'),
        ),
    ]
