# Generated by Django 5.2.7 on 2025-12-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0184_update_default_values_carte_identite_universal'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='devise_monnaie',
            field=models.CharField(blank=True, help_text='Devise utilisée dans le pays (ex: XOF, EUR, USD, etc.)', max_length=10, null=True, verbose_name='Devise de la monnaie'),
        ),
    ]
