# Generated by Django 5.2.7 on 2025-12-22 08:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0185_add_devise_monnaie_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='montant_facturation_annuelle',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Montant annuel unique à payer à l'inscription/réinscription (établissements publics uniquement)", max_digits=10, null=True, verbose_name='Montant de facturation annuelle'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='montant_frais_inscription',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Montant des frais d'inscription/réinscription (établissements privés uniquement)", max_digits=10, null=True, verbose_name="Montant des frais d'inscription"),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='montant_mensualite',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant de la mensualité mensuelle (établissements privés uniquement)', max_digits=10, null=True, verbose_name='Montant de la mensualité'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='type_etablissement_comptabilite',
            field=models.CharField(choices=[('public', 'Établissement public'), ('prive', 'Établissement privé')], default='prive', help_text='Détermine le système de facturation : Public (annuel unique) ou Privé (inscription + mensualités)', max_length=10, verbose_name="Type d'établissement (comptabilité)"),
        ),
        migrations.CreateModel(
            name='ComptabiliteEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_paiement', models.CharField(choices=[('a_jour', 'À jour'), ('en_retard', 'En retard'), ('impaye', 'Impayé')], default='a_jour', max_length=20, verbose_name='Statut de paiement')),
                ('date_derniere_verification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière vérification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptabilites_eleves', to='school_admin.anneescolaire', verbose_name='Année scolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptabilites', to='school_admin.eleve', verbose_name='Élève')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptabilites_eleves', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Comptabilité élève',
                'verbose_name_plural': 'Comptabilités élèves',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='FraisInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('en_retard', 'En retard')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('type_frais', models.CharField(choices=[('inscription', 'Inscription'), ('reinscription', 'Réinscription')], max_length=20, verbose_name='Type de frais')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_inscriptions', to='school_admin.anneescolaire', verbose_name='Année scolaire')),
                ('comptabilite_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_inscriptions', to='school_admin.comptabiliteeleve', verbose_name='Comptabilité élève')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_inscriptions', to='school_admin.eleve', verbose_name='Élève')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_inscriptions', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': "Frais d'inscription",
                'verbose_name_plural': "Frais d'inscription",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Mensualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(help_text='Numéro du mois (1-12)', verbose_name='Mois')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('en_retard', 'En retard'), ('impaye', 'Impayé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('periode', models.CharField(help_text='Ex: Janvier 2025', max_length=50, verbose_name='Période')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualites', to='school_admin.anneescolaire', verbose_name='Année scolaire')),
                ('comptabilite_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualites', to='school_admin.comptabiliteeleve', verbose_name='Comptabilité élève')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualites', to='school_admin.eleve', verbose_name='Élève')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualites', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Mensualité',
                'verbose_name_plural': 'Mensualités',
                'ordering': ['annee', 'mois'],
            },
        ),
        migrations.CreateModel(
            name='PaiementEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paiement', models.CharField(choices=[('frais_inscription', "Frais d'inscription"), ('mensualite', 'Mensualité'), ('autre', 'Autre')], max_length=30, verbose_name='Type de paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de paiement')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('carte', 'Carte bancaire'), ('autre', 'Autre')], max_length=20, verbose_name='Mode de paiement')),
                ('reference_paiement', models.CharField(blank=True, help_text='Numéro de chèque, référence virement, etc.', max_length=100, null=True, verbose_name='Référence de paiement')),
                ('notes', models.TextField(blank=True, help_text='Notes supplémentaires sur le paiement', null=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_eleves', to='school_admin.anneescolaire', verbose_name='Année scolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='school_admin.eleve', verbose_name='Élève')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_eleves', to='school_admin.etablissement', verbose_name='Établissement')),
                ('frais_inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='school_admin.fraisinscription', verbose_name="Frais d'inscription")),
                ('mensualite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='school_admin.mensualite', verbose_name='Mensualité')),
            ],
            options={
                'verbose_name': 'Paiement élève',
                'verbose_name_plural': 'Paiements élèves',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.AddIndex(
            model_name='comptabiliteeleve',
            index=models.Index(fields=['eleve', 'annee_scolaire'], name='school_admi_eleve_i_d4b7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='comptabiliteeleve',
            index=models.Index(fields=['etablissement', 'statut_paiement'], name='school_admi_etablis_03c65d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='comptabiliteeleve',
            unique_together={('eleve', 'annee_scolaire')},
        ),
        migrations.AddIndex(
            model_name='fraisinscription',
            index=models.Index(fields=['eleve', 'annee_scolaire'], name='school_admi_eleve_i_c7d264_idx'),
        ),
        migrations.AddIndex(
            model_name='fraisinscription',
            index=models.Index(fields=['etablissement', 'statut'], name='school_admi_etablis_e46a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='mensualite',
            index=models.Index(fields=['eleve', 'annee_scolaire', 'mois', 'annee'], name='school_admi_eleve_i_57eb96_idx'),
        ),
        migrations.AddIndex(
            model_name='mensualite',
            index=models.Index(fields=['etablissement', 'statut'], name='school_admi_etablis_c15674_idx'),
        ),
        migrations.AddIndex(
            model_name='mensualite',
            index=models.Index(fields=['date_echeance'], name='school_admi_date_ec_a5a2bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mensualite',
            unique_together={('eleve', 'annee_scolaire', 'mois', 'annee')},
        ),
        migrations.AddIndex(
            model_name='paiementeleve',
            index=models.Index(fields=['eleve', 'annee_scolaire'], name='school_admi_eleve_i_9bf117_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementeleve',
            index=models.Index(fields=['etablissement', 'date_paiement'], name='school_admi_etablis_fc64ef_idx'),
        ),
    ]
