# Generated by Django 5.2.7 on 2025-12-22 09:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0186_add_comptabilite_fields_to_etablissement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresComptabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_frais_inscription', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text="Montant des frais d'inscription (établissements privés)", max_digits=10, null=True, verbose_name="Montant des frais d'inscription")),
                ('montant_frais_reinscription', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text="Montant des frais de réinscription (peut être différent de l'inscription)", max_digits=10, null=True, verbose_name='Montant des frais de réinscription')),
                ('montant_mensualite', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Montant de la mensualité mensuelle (établissements privés)', max_digits=10, null=True, verbose_name='Montant de la mensualité')),
                ('montant_facturation_annuelle', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Montant annuel unique à payer (établissements publics)', max_digits=10, null=True, verbose_name='Montant de facturation annuelle')),
                ('type_facturation', models.CharField(choices=[('mensuel', 'Facturation mensuelle'), ('annuel', 'Facturation annuelle')], default='mensuel', help_text='Détermine si la facturation est mensuelle ou annuelle', max_length=20, verbose_name='Type de facturation')),
                ('autoriser_retards', models.BooleanField(default=True, help_text='Si activé, les élèves peuvent avoir des paiements en retard', verbose_name='Autoriser les retards de paiement')),
                ('autoriser_paiements_partiels', models.BooleanField(default=True, help_text='Si activé, les élèves peuvent payer partiellement leurs frais', verbose_name='Autoriser les paiements partiels')),
                ('delai_tolerance_retard', models.PositiveIntegerField(default=15, help_text="Nombre de jours après l'échéance avant de considérer un paiement en retard", verbose_name='Délai de tolérance pour retard (jours)')),
                ('envoyer_rappels_automatiques', models.BooleanField(default=True, help_text='Si activé, des rappels seront envoyés pour les paiements en retard', verbose_name='Envoyer des rappels automatiques')),
                ('jours_avant_rappel', models.PositiveIntegerField(default=7, help_text="Nombre de jours avant l'échéance pour envoyer un rappel", verbose_name='Jours avant échéance pour rappel')),
                ('jours_apres_retard_rappel', models.PositiveIntegerField(default=3, help_text='Nombre de jours après le retard pour envoyer un rappel', verbose_name='Jours après retard pour rappel')),
                ('mois_debut_facturation', models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], default=9, help_text='Mois de début de la période de facturation (1-12, ex: 9 pour septembre)', verbose_name='Mois de début de facturation')),
                ('mois_fin_facturation', models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], default=6, help_text='Mois de fin de la période de facturation (1-12, ex: 6 pour juin)', verbose_name='Mois de fin de facturation')),
                ('appliquer_remise_famille_nombreuse', models.BooleanField(default=False, help_text='Si activé, une remise sera appliquée pour les familles nombreuses', verbose_name='Appliquer remise famille nombreuse')),
                ('pourcentage_remise_famille_nombreuse', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pourcentage de remise à appliquer (ex: 10.00 pour 10%)', max_digits=5, verbose_name='Pourcentage de remise famille nombreuse')),
                ('nombre_enfants_minimum_remise', models.PositiveIntegerField(default=3, help_text="Nombre minimum d'enfants dans l'établissement pour bénéficier de la remise", verbose_name="Nombre minimum d'enfants pour remise")),
                ('nombre_max_paiements_partiels', models.PositiveIntegerField(default=3, help_text='Nombre maximum de paiements partiels autorisés pour une facture', verbose_name='Nombre maximum de paiements partiels')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('etablissement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres_comptabilite', to='school_admin.etablissement', verbose_name='Établissement')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametres_comptabilite_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Paramètres de comptabilité',
                'verbose_name_plural': 'Paramètres de comptabilité',
                'ordering': ['-date_modification'],
            },
        ),
    ]
