# Generated by Django 5.2.7 on 2025-12-22 09:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0187_add_parametres_comptabilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraisinscription',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Montant déjà payé pour ces frais d'inscription", max_digits=10, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='mensualite',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant déjà payé pour cette mensualité', max_digits=10, verbose_name='Montant payé'),
        ),
    ]
