# Generated by Django 5.2.7 on 2025-12-22 11:04

from decimal import Decimal
from django.db import migrations, models


def calculer_reste_a_payer(apps, schema_editor):
    """
    Calcule et met à jour le reste_a_payer pour tous les frais d'inscription existants
    """
    FraisInscription = apps.get_model('school_admin', 'FraisInscription')
    
    for frais in FraisInscription.objects.all():
        reste = frais.montant - frais.montant_paye
        frais.reste_a_payer = reste if reste > Decimal('0.00') else Decimal('0.00')
        frais.save(update_fields=['reste_a_payer'])


def reverse_calculer_reste_a_payer(apps, schema_editor):
    """
    Fonction de rollback - remet reste_a_payer à 0
    """
    FraisInscription = apps.get_model('school_admin', 'FraisInscription')
    
    for frais in FraisInscription.objects.all():
        frais.reste_a_payer = Decimal('0.00')
        frais.save(update_fields=['reste_a_payer'])


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0188_add_montant_paye_to_frais_mensualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraisinscription',
            name='reste_a_payer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Montant restant à payer pour ces frais d'inscription", max_digits=10, verbose_name='Reste à payer'),
        ),
        migrations.RunPython(calculer_reste_a_payer, reverse_calculer_reste_a_payer),
    ]
