# Generated by Django 5.2.7 on 2025-12-22 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0190_update_reste_a_payer_existing_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescomptabilite',
            name='jour_versement',
            field=models.PositiveIntegerField(default=5, help_text='Jour du mois où les paiements mensuels doivent être effectués (1-31, ex: 5 pour le 5 de chaque mois)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Jour de versement mensuel'),
        ),
        migrations.AddField(
            model_name='parametrescomptabilite',
            name='paiement_en_avance',
            field=models.BooleanField(default=False, help_text="Si activé, le paiement effectué le jour de versement est pour le mois en cours. Sinon, c'est pour le mois précédent.", verbose_name='Paiement en avance'),
        ),
    ]
