# Generated by Django 5.2.7 on 2025-12-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0191_add_jour_versement_paiement_avance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensualite',
            name='date_dernier_paiement_partiel',
            field=models.DateTimeField(blank=True, help_text='Date du dernier paiement partiel effectué pour cette mensualité', null=True, verbose_name='Date du dernier paiement partiel'),
        ),
        migrations.AlterField(
            model_name='mensualite',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('en_retard', 'En retard'), ('impaye', 'Impayé'), ('mp', 'Mois Précédents')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
    ]
