# Generated by Django 5.2.7 on 2025-12-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0192_add_date_dernier_paiement_partiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personneladministratif',
            name='fonction',
            field=models.CharField(choices=[('directeur_adjoint_primaire', 'Directeur Adjoint (École Primaire)'), ('principal_adjoint', 'Principal Adjoint (Collège)'), ('proviseur_adjoint', 'Proviseur Adjoint (Lycée)'), ('directeur_principal', 'Directeur Principal (Établissement Mixte)'), ('directeur_section_primaire', 'Directeur de Section Primaire'), ('principal_section_college', 'Principal de Section Collège'), ('proviseur_section_lycee', 'Proviseur de Section Lycée'), ('secretaire_principal', 'Secrétaire Principal'), ('secretaire', 'Secrétaire'), ('gestionnaire', 'Gestionnaire'), ('surveillant', 'Surveillant'), ('censeur', 'Censeur'), ('censeur_etudes', 'Censeur des Études (Collèges & Lycées)'), ('censeur_adjoint', 'Censeur Adjoint (Lycées)'), ('censeur_premier_cycle', 'Censeur du Premier Cycle (6e à 3e)'), ('censeur_second_cycle', 'Censeur du Second Cycle (2nde à Tle)'), ('censeur_pedagogie', 'Censeur chargé de la Pédagogie'), ('censeur_vie_scolaire', 'Censeur chargé de la Vie Scolaire'), ('surveillant_general', 'Surveillant Général'), ('secretaire_vie_scolaire', 'Secrétaire de Vie Scolaire'), ('administrateur', 'Administrateur Système'), ('autre', 'Autre')], max_length=50, verbose_name='Fonction'),
        ),
    ]
