# Generated by Django 5.2.7 on 2026-02-24 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0195_parametrescomptabilitegroupeclasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='niveau_lmd',
            field=models.CharField(blank=True, help_text='Utilisé pour les établissements supérieurs sans structure LMD configurée', max_length=10, null=True, verbose_name='Niveau LMD (L1, L2, M1, etc.)'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='type_etablissement',
            field=models.CharField(choices=[('primary', 'École Primaire'), ('collège', 'Collège'), ('lycée', 'Lycée'), ('collège_lycée', 'Collège + Lycée'), ('mixte', 'Établissement Mixte'), ('superieur', 'Établissement Supérieur')], max_length=20, verbose_name="Type d'établissement"),
        ),
        migrations.CreateModel(
            name='AcademicCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du cycle')),
                ('code', models.CharField(choices=[('L', 'Licence'), ('M', 'Master'), ('D', 'Doctorat')], max_length=5, verbose_name='Code')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_cycles', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Cycle académique',
                'verbose_name_plural': 'Cycles académiques',
                'ordering': ['etablissement', 'ordre', 'code'],
                'unique_together': {('etablissement', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom du niveau')),
                ('code', models.CharField(choices=[('L1', 'L1 (Licence 1)'), ('L2', 'L2 (Licence 2)'), ('L3', 'L3 (Licence 3)'), ('M1', 'M1 (Master 1)'), ('M2', 'M2 (Master 2)'), ('D1', 'D1 (Doctorat 1)'), ('D2', 'D2 (Doctorat 2)'), ('D3', 'D3 (Doctorat 3)')], max_length=10, verbose_name='Code')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_levels', to='school_admin.academiccycle', verbose_name='Cycle académique')),
            ],
            options={
                'verbose_name': 'Niveau académique',
                'verbose_name_plural': 'Niveaux académiques',
                'ordering': ['cycle', 'ordre', 'code'],
                'unique_together': {('cycle', 'code')},
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='academic_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='school_admin.academiclevel', verbose_name='Niveau académique (LMD)'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la filière')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Filière / Département',
                'verbose_name_plural': 'Filières / Départements',
                'ordering': ['etablissement', 'ordre', 'nom'],
                'unique_together': {('etablissement', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='school_admin.department', verbose_name='Filière / Département'),
        ),
    ]
