# Generated by Django 5.2.7 on 2026-02-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0196_add_academic_structure_lmd'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(condition=models.Q(('niveau__in', ['maternelle', 'primaire', 'college', 'lycee'])), fields=('etablissement', 'niveau', 'nom'), name='unique_classe_primaire_secondaire'),
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(condition=models.Q(('niveau', 'superieur'), ('niveau_lmd__isnull', False)), fields=('etablissement', 'niveau_lmd', 'nom'), name='unique_classe_superieur_lmd'),
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(condition=models.Q(('niveau', 'superieur'), ('niveau_lmd__isnull', True)), fields=('etablissement', 'nom'), name='unique_classe_superieur_sans_lmd'),
        ),
    ]
