# Generated by Django 5.2.7 on 2026-02-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0197_alter_classe_unique_constraints_lmd'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classe',
            name='unique_classe_superieur_lmd',
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau_libelle',
            field=models.CharField(blank=True, help_text='Détail du niveau lorsque « Autre » est sélectionné (ex: Formation Court Métrage 6 mois)', max_length=100, null=True, verbose_name='Niveau personnalisé (si Autre)'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveau_lmd',
            field=models.CharField(blank=True, help_text='LMD, BTS, DUT, Certificat ou Autre pour les établissements supérieurs', max_length=20, null=True, verbose_name='Niveau (L1, BTS, DUT, etc.)'),
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(condition=models.Q(('niveau', 'superieur'), ('niveau_lmd__isnull', False), models.Q(('niveau_lmd', 'AUTRE'), _negated=True)), fields=('etablissement', 'niveau_lmd', 'nom'), name='unique_classe_superieur_standard'),
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(condition=models.Q(('niveau', 'superieur'), ('niveau_lmd', 'AUTRE'), ('niveau_libelle__isnull', False)), fields=('etablissement', 'niveau_libelle', 'nom'), name='unique_classe_superieur_autre'),
        ),
    ]
