# Generated by Django 5.2.7 on 2026-02-24 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0198_add_niveau_libelle_and_extend_superieur_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='credits',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Utilisé pour enseignement supérieur (si matière dans un module)', max_digits=5, null=True, verbose_name='Crédits'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='coefficient',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='Utilisé pour primaire/secondaire', max_digits=3, verbose_name='Coefficient'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du module')),
                ('code', models.CharField(max_length=20, verbose_name='Code du module')),
                ('niveau_lmd', models.CharField(blank=True, help_text='L1, L2, BTS, DUT, etc.', max_length=20, null=True, verbose_name='Niveau LMD')),
                ('credits', models.DecimalField(blank=True, decimal_places=2, help_text='Si renseigné, utilisé tel quel. Sinon, somme des crédits des matières.', max_digits=5, null=True, verbose_name='Crédits directs du module')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='school_admin.department', verbose_name='Filière')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['etablissement', 'ordre', 'nom'],
                'unique_together': {('etablissement', 'code')},
            },
        ),
        migrations.AddField(
            model_name='matiere',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Module auquel appartient la matière (enseignement supérieur)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres', to='school_admin.module', verbose_name='Module'),
        ),
    ]
