# Generated by Django 5.2.7 on 2026-02-24 05:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0200_add_credits_to_moyenne_periode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matiere',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Filière à laquelle appartient la matière (obligatoire pour enseignement supérieur)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres', to='school_admin.department', verbose_name='Filière'),
        ),
        migrations.AlterField(
            model_name='moyenneperiode',
            name='credits',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Crédits de la matière au moment du calcul (enseignement supérieur)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Crédits utilisés au calcul (supérieur)'),
        ),
        migrations.AddConstraint(
            model_name='matiere',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('nom', 'etablissement', 'department'), name='matiere_unique_par_filiere'),
        ),
        migrations.AddConstraint(
            model_name='matiere',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True)), fields=('nom', 'etablissement'), name='matiere_unique_sans_filiere'),
        ),
    ]
