# Generated by Django 5.2.7 on 2026-02-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0201_add_department_to_matiere'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matiere',
            name='matiere_unique_par_filiere',
        ),
        migrations.AddConstraint(
            model_name='matiere',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False), ('module__isnull', False)), fields=('nom', 'etablissement', 'department', 'module'), name='matiere_unique_par_module'),
        ),
        migrations.AddConstraint(
            model_name='matiere',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False), ('module__isnull', True)), fields=('nom', 'etablissement', 'department'), name='matiere_unique_par_filiere_sans_module'),
        ),
    ]
