# Generated by Django 5.2.7 on 2026-03-16 20:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def migrate_module_classes_data(apps, schema_editor):
    """Migre les données module-classes vers ModuleClasse avec credits du module."""
    Module = apps.get_model('school_admin', 'Module')
    ModuleClasse = apps.get_model('school_admin', 'ModuleClasse')
    for module in Module.objects.all():
        credits_val = module.credits if module.credits is not None else Decimal('0')
        for classe in module.classes.all():
            ModuleClasse.objects.get_or_create(
                module=module,
                classe=classe,
                defaults={'credits': credits_val}
            )


def reverse_migrate(apps, schema_editor):
    """Pas de reverse - les données restent dans l'ancienne structure."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0203_module_classes_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Crédits pour cette classe')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_classe_credits', to='school_admin.classe', verbose_name='Classe')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_classes', to='school_admin.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Module-Classe (crédits)',
                'verbose_name_plural': 'Modules-Classes (crédits)',
                'unique_together': {('module', 'classe')},
            },
        ),
        migrations.RunPython(migrate_module_classes_data, reverse_migrate),
        migrations.RemoveField(
            model_name='module',
            name='classes',
        ),
        migrations.AddField(
            model_name='module',
            name='classes',
            field=models.ManyToManyField(blank=True, help_text='Classes qui suivent ce module avec crédits spécifiques par classe', related_name='modules', through='school_admin.ModuleClasse', to='school_admin.classe', verbose_name='Classes concernées'),
        ),
        migrations.RemoveField(
            model_name='module',
            name='credits',
        ),
    ]
