# Generated by Django 5.2.7 on 2026-03-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0204_module_classe_credits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['etablissement', 'ordre', 'nom'], 'verbose_name': 'Spécialité', 'verbose_name_plural': 'Spécialités'},
        ),
        migrations.AddField(
            model_name='department',
            name='domaine',
            field=models.CharField(blank=True, help_text='Ex: Sciences et Technologies, Sciences Humaines', max_length=255, verbose_name='Domaine'),
        ),
        migrations.AddField(
            model_name='department',
            name='mention',
            field=models.CharField(blank=True, help_text='Ex: Informatique, Logistique', max_length=255, verbose_name='Mention'),
        ),
        migrations.AlterField(
            model_name='department',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom de la spécialité'),
        ),
    ]
