# Generated by Django 5.2.7 on 2026-03-26 10:33

import django.db.models.deletion
from django.db import migrations, models


def seed_catalogue_examens_concours(apps, schema_editor):
    Catalogue = apps.get_model('school_admin', 'CatalogueExamenConcours')
    rows = [
        ('BTS', 'Brevet de Technicien Supérieur (BTS)', 'Diplôme national niveau bac+2', 'diplome_pro', 10),
        ('BT', 'Brevet de Technicien (BT)', 'Formation professionnelle courte', 'diplome_pro', 20),
        ('DUT', 'DUT / accès parallèle', 'Diplôme universitaire de technologie', 'diplome_pro', 30),
        ('BUT', 'Bachelor universitaire de technologie (BUT)', '', 'diplome_pro', 40),
        ('LP', 'Licence professionnelle', '', 'diplome_pro', 50),
        ('CAP', "Certificat d'aptitude professionnelle (CAP)", '', 'diplome_pro', 60),
        ('BP', 'Brevet professionnel (BP)', '', 'diplome_pro', 70),
        ('CONCOURS_BTS', 'Concours ou sélection BTS', 'Accès parallèle, passerelles LMD → BTS', 'concours', 80),
        ('CONCOURS_BT', 'Concours ou sélection BT', '', 'concours', 90),
        ('CONCOURS_ADMIN', 'Concours administratifs', 'Fonction publique, organismes publics', 'concours', 100),
        ('EXAMEN_BLANC', 'Examens blancs / sessions préparatoires nationales', '', 'preparation', 110),
        ('CERTIF_PRO', 'Certification professionnelle reconnue', 'RNCP, organismes certificateurs', 'certification', 120),
        ('VAE', 'Valorisation des acquis de l’expérience (VAE)', '', 'autre', 130),
        ('AUTRE_INSTIT', 'Autre examen ou concours institutionnel / régional', '', 'autre', 140),
    ]
    for code, libelle, desc, cat, ordre in rows:
        Catalogue.objects.get_or_create(
            code=code,
            defaults={
                'libelle': libelle,
                'description': desc,
                'categorie': cat,
                'ordre': ordre,
                'actif': True,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0206_moyenneperiode_note_rattrapage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueExamenConcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=160, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('categorie', models.CharField(blank=True, help_text='ex. diplome_pro, concours, certification', max_length=40, verbose_name='Catégorie')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Examen / concours (catalogue)',
                'verbose_name_plural': 'Examens et concours (catalogue)',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='ClasseParcoursExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_examens_concours', to='school_admin.classe', verbose_name='Classe')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_classes', to='school_admin.catalogueexamenconcours', verbose_name='Examen ou concours')),
            ],
            options={
                'verbose_name': 'Classe — examen ou concours',
                'verbose_name_plural': 'Classes — examens et concours',
                'unique_together': {('classe', 'option')},
            },
        ),
        migrations.RunPython(seed_catalogue_examens_concours, noop_reverse),
    ]
