# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0209_moduleclasse_numero_ue'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodescolaire',
            name='niveau_lmd',
            field=models.CharField(
                blank=True,
                default='',
                help_text='L1, L2, … pour les périodes propres à un niveau (supérieur uniquement).',
                max_length=20,
                verbose_name='Niveau LMD',
            ),
        ),
        migrations.AlterModelOptions(
            name='periodescolaire',
            options={
                'ordering': ['annee_scolaire', 'niveau_lmd', 'date_debut'],
                'verbose_name': 'Période scolaire',
                'verbose_name_plural': 'Périodes scolaires',
            },
        ),
        migrations.AlterUniqueTogether(
            name='periodescolaire',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='periodescolaire',
            constraint=models.UniqueConstraint(
                fields=('etablissement', 'nom_periode', 'annee_scolaire', 'niveau_lmd'),
                name='unique_periode_par_niveau_annee',
            ),
        ),
    ]
