# Generated by Django 5.2.6 on 2026-09-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0211_moduleclasse_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='personneladministratif',
            name='date_embauche',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AddField(
            model_name='personneladministratif',
            name='prix_volume_horaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix du volume horaire (FCFA/heure)'),
        ),
        migrations.AddField(
            model_name='personneladministratif',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], default='', max_length=1, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='prix_volume_horaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix du volume horaire (FCFA/heure)'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], default='', max_length=1, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='date_embauche',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
    ]
