# Generated by Django 5.2.6 on 2026-09-09 22:08

import django.db.models.deletion
import school_admin.model.employe_dossier_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0212_employe_dossier_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=200, verbose_name='Libellé du document')),
                ('fichier', models.FileField(upload_to=school_admin.model.employe_dossier_model.employe_document_upload_to, verbose_name='Fichier')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('personnel_administratif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='school_admin.personneladministratif', verbose_name='Personnel administratif')),
                ('professeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='school_admin.professeur', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Document employé',
                'verbose_name_plural': 'Documents employés',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='DossierEmployeComplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=150, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(blank=True, max_length=100, verbose_name='Nationalité')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('numero_cni', models.CharField(blank=True, max_length=50, verbose_name="N° pièce d'identité (CNI / passeport)")),
                ('numero_cnss', models.CharField(blank=True, max_length=50, verbose_name='N° CNSS / sécurité sociale')),
                ('type_contrat', models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('vacataire', 'Vacataire'), ('stage', 'Stage / Alternance'), ('convention', 'Convention'), ('prestation', 'Prestation de service'), ('autre', 'Autre')], max_length=20, verbose_name='Type de contrat')),
                ('date_fin_contrat', models.DateField(blank=True, null=True, verbose_name='Date de fin de contrat')),
                ('salaire_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salaire de base (FCFA)')),
                ('banque', models.CharField(blank=True, max_length=120, verbose_name='Banque')),
                ('numero_compte_bancaire', models.CharField(blank=True, max_length=80, verbose_name='N° compte / RIB')),
                ('diplome_plus_eleve', models.CharField(blank=True, max_length=150, verbose_name='Diplôme le plus élevé')),
                ('numero_autorisation', models.CharField(blank=True, max_length=80, verbose_name="N° autorisation d'enseignement / agrément")),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=120, verbose_name="Contact d'urgence — nom")),
                ('contact_urgence_telephone', models.CharField(blank=True, max_length=30, verbose_name="Contact d'urgence — téléphone")),
                ('contact_urgence_lien', models.CharField(blank=True, max_length=80, verbose_name="Contact d'urgence — lien (conjoint, parent…)")),
                ('observations', models.TextField(blank=True, verbose_name='Observations / notes administratives')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('personnel_administratif', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossier_complementaire', to='school_admin.personneladministratif', verbose_name='Personnel administratif')),
                ('professeur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossier_complementaire', to='school_admin.professeur', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Dossier employé complémentaire',
                'verbose_name_plural': 'Dossiers employés complémentaires',
            },
        ),
    ]
