# Generated by Django 5.2.6 on 2026-09-14 09:26

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0220_recouvrement_vague1'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('minutes', models.PositiveIntegerField(default=0, help_text='Durée des créneaux EDT de ce jour.', verbose_name='Minutes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Absence enseignant',
                'verbose_name_plural': 'Absences enseignants',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DepenseEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depense', models.DateField(verbose_name='Date')),
                ('motif', models.CharField(choices=[('salaire', 'Salaire / vacataire'), ('loyer', 'Loyer'), ('electricite', 'Électricité / eau'), ('fournitures', 'Fournitures'), ('carburant', 'Carburant / transport'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Motif')),
                ('libelle', models.CharField(blank=True, default='', help_text='Optionnel. Ex. : Orange Money septembre, loyer bâtiment A.', max_length=160, verbose_name='Précision')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Enregistré le')),
            ],
            options={
                'verbose_name': "Dépense d'établissement",
                'verbose_name_plural': "Dépenses d'établissement",
                'ordering': ['-date_depense', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaieProfesseurPeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Début de période')),
                ('date_fin', models.DateField(verbose_name='Fin de période')),
                ('heures', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Heures')),
                ('montant_brut', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Brut')),
                ('retenue_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Charges %')),
                ('montant_net', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Net versé')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Payé le')),
            ],
            options={
                'verbose_name': 'Paie professeur',
                'verbose_name_plural': 'Paies professeurs',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.RenameIndex(
            model_name='fraisannexe',
            new_name='school_admi_eleve_i_16da4f_idx',
            old_name='fraisann_eleve_annee_idx',
        ),
        migrations.RenameIndex(
            model_name='fraisannexe',
            new_name='school_admi_etablis_5a2666_idx',
            old_name='fraisann_etab_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='fraisannexe',
            new_name='school_admi_code_2edacd_idx',
            old_name='fraisann_code_idx',
        ),
        migrations.RenameIndex(
            model_name='moratoire',
            new_name='school_admi_etablis_590108_idx',
            old_name='moratoire_etab_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='moratoire',
            new_name='school_admi_eleve_i_8699ce_idx',
            old_name='moratoire_eleve_annee_idx',
        ),
        migrations.RenameIndex(
            model_name='paiementeleve',
            new_name='school_admi_etablis_a70b03_idx',
            old_name='paiemeleve_etab_recu_idx',
        ),
        migrations.RenameIndex(
            model_name='relanceimpaye',
            new_name='school_admi_etablis_0ebfe6_idx',
            old_name='relance_etab_date_idx',
        ),
        migrations.RenameIndex(
            model_name='relanceimpaye',
            new_name='school_admi_eleve_i_60b252_idx',
            old_name='relance_eleve_annee_idx',
        ),
        migrations.RenameIndex(
            model_name='syncaction',
            new_name='school_admi_utilisa_27c268_idx',
            old_name='school_admi_utilisa_sync_idx',
        ),
        migrations.RenameIndex(
            model_name='syncaction',
            new_name='school_admi_resourc_9323e6_idx',
            old_name='school_admi_resourc_sync_idx',
        ),
        migrations.AlterField(
            model_name='notificationparent',
            name='type_notification',
            field=models.CharField(choices=[('presence', 'Présence / Absence'), ('note', 'Note individuelle'), ('moyenne', 'Moyenne de période'), ('bulletin', 'Bulletin disponible'), ('sanction', 'Sanction appliquée'), ('evaluation', 'Évaluation programmée'), ('information', 'Information générale'), ('scolarite', 'Scolarité / impayé')], max_length=20, verbose_name="Type d'évènement"),
        ),
        migrations.AlterField(
            model_name='paiementeleve',
            name='reference_paiement',
            field=models.CharField(blank=True, help_text='N° Wave / Orange Money / MTN, chèque ou virement', max_length=100, null=True, verbose_name='Référence de paiement'),
        ),
        migrations.AddField(
            model_name='absenceenseignant',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences_enseignants', to='school_admin.etablissement', verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='absenceenseignant',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences_enseignant', to='school_admin.professeur', verbose_name='Professeur absent'),
        ),
        migrations.AddField(
            model_name='absenceenseignant',
            name='remplacant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacements_effectues', to='school_admin.professeur', verbose_name='A fait le cours'),
        ),
        migrations.AddField(
            model_name='depenseetablissement',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_caisse', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='depenseetablissement',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_caisse_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par'),
        ),
        migrations.AddField(
            model_name='depenseetablissement',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses_caisse', to='school_admin.etablissement', verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='paieprofesseurperiode',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paies_professeurs', to='school_admin.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='paieprofesseurperiode',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paies_professeurs_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par'),
        ),
        migrations.AddField(
            model_name='paieprofesseurperiode',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paies_professeurs', to='school_admin.etablissement', verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='paieprofesseurperiode',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paies_periodes', to='school_admin.professeur', verbose_name='Professeur'),
        ),
        migrations.AddConstraint(
            model_name='absenceenseignant',
            constraint=models.UniqueConstraint(fields=('professeur', 'date'), name='uniq_absence_enseignant_jour'),
        ),
        migrations.AddConstraint(
            model_name='paieprofesseurperiode',
            constraint=models.UniqueConstraint(fields=('professeur', 'date_debut', 'date_fin'), name='uniq_paie_professeur_periode'),
        ),
    ]
