# Generated by Django 5.2.6 on 2026-09-14 15:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0221_caisse_paie_absences'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12, verbose_name='Numéro')),
                ('libelle', models.CharField(max_length=160, verbose_name='Libellé')),
                ('classe', models.CharField(choices=[('1', 'Classe 1 — Financement permanent'), ('2', 'Classe 2 — Actif immobilisé'), ('3', 'Classe 3 — Stocks'), ('4', 'Classe 4 — Tiers'), ('5', 'Classe 5 — Trésorerie'), ('6', 'Classe 6 — Charges'), ('7', 'Classe 7 — Produits'), ('8', 'Classe 8 — Autres charges et produits')], max_length=1, verbose_name='Classe')),
                ('nature', models.CharField(choices=[('actif', 'Actif'), ('passif', 'Passif'), ('charge', 'Charge'), ('produit', 'Produit'), ('hors', 'Hors bilan')], default='actif', max_length=10)),
                ('est_auxiliaire', models.BooleanField(default=False, verbose_name='Auxiliaire')),
                ('actif', models.BooleanField(default=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_comptables', to='school_admin.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Compte comptable',
                'verbose_name_plural': 'Comptes comptables',
                'ordering': ['numero'],
                'unique_together': {('etablissement', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ExerciceComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex. 2026', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('cloture', 'Clôturé')], default='ouvert', max_length=10)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices_comptables', to='school_admin.anneescolaire')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices_comptables', to='school_admin.etablissement')),
            ],
            options={
                'verbose_name': 'Exercice comptable',
                'verbose_name_plural': 'Exercices comptables',
                'ordering': ['-date_debut'],
                'unique_together': {('etablissement', 'libelle')},
            },
        ),
        migrations.CreateModel(
            name='FournisseurEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=160)),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('actif', models.BooleanField(default=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='school_admin.etablissement')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FactureFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('libelle', models.CharField(max_length=200)),
                ('date_facture', models.DateField()),
                ('date_echeance', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('statut', models.CharField(choices=[('a_payer', 'À payer'), ('partiel', 'Partiellement payée'), ('payee', 'Payée')], default='a_payer', max_length=12)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_fournisseurs', to='school_admin.etablissement')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='school_admin.fournisseuretablissement')),
            ],
            options={
                'verbose_name': 'Facture fournisseur',
                'verbose_name_plural': 'Factures fournisseurs',
                'ordering': ['date_echeance'],
            },
        ),
        migrations.CreateModel(
            name='Immobilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=160)),
                ('categorie', models.CharField(choices=[('batiment', 'Bâtiment'), ('bus', 'Flotte de bus'), ('informatique', 'Parc informatique'), ('mobilier', 'Mobilier de classe'), ('autre', 'Autre')], default='autre', max_length=40)),
                ('date_acquisition', models.DateField()),
                ('valeur_origine', models.DecimalField(decimal_places=2, max_digits=14)),
                ('duree_annees', models.PositiveIntegerField(default=5)),
                ('actif', models.BooleanField(default=True)),
                ('compte_immobilisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immobilisations', to='school_admin.comptecomptable')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobilisations', to='school_admin.etablissement')),
            ],
            options={
                'verbose_name': 'Immobilisation',
                'verbose_name_plural': 'Immobilisations',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='JournalComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('libelle', models.CharField(max_length=80)),
                ('actif', models.BooleanField(default=True)),
                ('compte_contrepartie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_contrepartie', to='school_admin.comptecomptable')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux_comptables', to='school_admin.etablissement')),
            ],
            options={
                'verbose_name': 'Journal comptable',
                'verbose_name_plural': 'Journaux comptables',
                'ordering': ['code'],
                'unique_together': {('etablissement', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=24)),
                ('date_ecriture', models.DateField()),
                ('libelle', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('source', models.CharField(blank=True, default='', help_text='paiement_eleve, depense, paie, od, virement…', max_length=40)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('validee', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('creee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_creees', to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures_comptables', to='school_admin.etablissement')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='school_admin.exercicecomptable')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='school_admin.journalcomptable')),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'ordering': ['-date_ecriture', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, default='', max_length=200)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('auxiliaire', models.CharField(blank=True, default='', max_length=80)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='school_admin.comptecomptable')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='school_admin.ecriturecomptable')),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écriture",
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MouvementTresorerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('virement_interne', 'Virement interne'), ('rapprochement', 'Rapprochement bancaire')], max_length=24)),
                ('date_mouvement', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('libelle', models.CharField(max_length=200)),
                ('pointe', models.BooleanField(default=False)),
                ('date_pointage', models.DateTimeField(blank=True, null=True)),
                ('ecriture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_tresorerie', to='school_admin.ecriturecomptable')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_tresorerie', to='school_admin.etablissement')),
            ],
            options={
                'verbose_name': 'Mouvement de trésorerie',
                'verbose_name_plural': 'Mouvements de trésorerie',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='PeriodeComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_periode', models.CharField(choices=[('mois', 'Mois'), ('trimestre', 'Trimestre'), ('semestre', 'Semestre')], default='mois', max_length=12)),
                ('libelle', models.CharField(max_length=40)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('verrouillee', models.BooleanField(default=False)),
                ('date_verrouillage', models.DateTimeField(blank=True, null=True)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='school_admin.exercicecomptable')),
            ],
            options={
                'verbose_name': 'Période comptable',
                'verbose_name_plural': 'Périodes comptables',
                'ordering': ['date_debut'],
            },
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['etablissement', 'date_ecriture'], name='school_admi_etablis_4632be_idx'),
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['source', 'source_id'], name='school_admi_source_890ae2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ecriturecomptable',
            unique_together={('etablissement', 'journal', 'numero')},
        ),
    ]
