# school_admin/personal_url/enseignant_url.py

from django.urls import path
from ..personal_views.enseignant_view import (
    dashboard_enseignant,
    gestion_classes_enseignant,
    gestion_eleves_enseignant,
    gestion_notes_enseignant,
    exercices_maison_enseignant,
    gestion_presence_enseignant,
    eleves_en_difficulte_enseignant,
    noter_eleves_enseignant,
    noter_examen_enseignant,
    voir_releve_notes,
    imprimer_releve_notes,
    imprimer_releve_notes_enseignant,
    api_releve_notes_modal,
    creer_evaluation_enseignant,
    liste_evaluations_enseignant,
    calculer_moyennes_classe,
    soumettre_releve_notes,
    liste_presence_enseignant,
    valider_presence_enseignant,
    detail_eleve_enseignant,
    modifier_presence_eleve,
    historique_presence_eleve,
    justifier_absence_eleve,
    detail_classe_enseignant,
    soumettre_sanction_eleve,
    historique_sanctions_eleve,
    liste_sanctions_classe,
    parametres_profil_enseignant,
    emploi_du_temps_enseignant,
    imprimer_tableau_presence_enseignant,
    notifications_enseignant,
    annonces_enseignant,
    justifications_notes_enseignant,
)

app_name = 'enseignant'

urlpatterns = [
    path('dashboard/enseignant/', dashboard_enseignant, name='dashboard_enseignant'),
    path('enseignant/classes/', gestion_classes_enseignant, name='gestion_classes'),
    path('enseignant/eleves/', gestion_eleves_enseignant, name='gestion_eleves'),
    path('enseignant/notes/', gestion_notes_enseignant, name='gestion_notes'),
    path('enseignant/justifications-notes/', justifications_notes_enseignant, name='justifications_notes'),
    path('enseignant/exercices/', exercices_maison_enseignant, name='exercices_maison'),
    path('enseignant/presence/', gestion_presence_enseignant, name='gestion_presence'),
    path('enseignant/eleves-difficulte/', eleves_en_difficulte_enseignant, name='eleves_en_difficulte'),
    path('enseignant/noter/<int:classe_id>/', noter_eleves_enseignant, name='noter_eleves'),
    path('enseignant/noter-examen/<int:classe_id>/', noter_examen_enseignant, name='noter_examen'),
    path('enseignant/noter-examen/<int:classe_id>/<int:session_id>/', noter_examen_enseignant, name='noter_examen_session'),
    path('enseignant/releve/<int:classe_id>/', voir_releve_notes, name='voir_releve'),
    path('enseignant/api/releve-modal/<int:classe_id>/', api_releve_notes_modal, name='api_releve_modal'),
    path('enseignant/imprimer-releve/<int:classe_id>/', imprimer_releve_notes, name='imprimer_releve'),
    path('enseignant/imprimer-releve-enseignant/<int:classe_id>/', imprimer_releve_notes_enseignant, name='imprimer_releve_enseignant'),
    path('enseignant/evaluation/creer/<int:classe_id>/', creer_evaluation_enseignant, name='creer_evaluation'),
    path('enseignant/evaluations/', liste_evaluations_enseignant, name='liste_evaluations'),
    path('enseignant/calculer-moyennes/<int:classe_id>/', calculer_moyennes_classe, name='calculer_moyennes'),
    path('enseignant/soumettre-releve/<int:classe_id>/', soumettre_releve_notes, name='soumettre_releve'),
    path('enseignant/presence/<int:classe_id>/', liste_presence_enseignant, name='liste_presence'),
    path('enseignant/valider-presence/<int:classe_id>/', valider_presence_enseignant, name='valider_presence'),
    path('enseignant/imprimer-tableau-presence/<int:classe_id>/', imprimer_tableau_presence_enseignant, name='imprimer_tableau_presence'),
    path('enseignant/eleve/<int:eleve_id>/', detail_eleve_enseignant, name='detail_eleve'),
    path('enseignant/modifier-presence/<int:presence_id>/', modifier_presence_eleve, name='modifier_presence'),
    path('enseignant/historique-presence/<int:eleve_id>/', historique_presence_eleve, name='historique_presence'),
    path('enseignant/justifier-absence/', justifier_absence_eleve, name='justifier_absence'),
    path('enseignant/classe/<int:classe_id>/', detail_classe_enseignant, name='detail_classe'),
    path('enseignant/soumettre-sanction/', soumettre_sanction_eleve, name='soumettre_sanction'),
    path('enseignant/historique-sanctions/<int:eleve_id>/', historique_sanctions_eleve, name='historique_sanctions'),
    path('enseignant/sanctions-classe/<int:classe_id>/', liste_sanctions_classe, name='liste_sanctions_classe'),
    path('enseignant/parametres-profil/', parametres_profil_enseignant, name='parametres_profil'),
    path('enseignant/emploi-du-temps/', emploi_du_temps_enseignant, name='emploi_du_temps'),
    path('enseignant/notifications/', notifications_enseignant, name='notifications_enseignant'),
    path('enseignant/annonces/', annonces_enseignant, name='annonces_enseignant'),
]

