"""
Django settings for school project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os

# ...

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'school_admin/static'),  # Ajouter le chemin des fichiers statiques de l'application
]
# Configuration des sessions - Connexion persistante "à vie"
# La session ne s'expire jamais tant que l'utilisateur ne se déconnecte pas manuellement
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # La session ne expire pas quand le navigateur est fermé
SESSION_SAVE_EVERY_REQUEST = True  # Renouveler la session à chaque requête pour la maintenir active
# Age de la session en secondes - 10 ans (connexion persistante)
# La session sera renouvelée automatiquement à chaque requête grâce à SESSION_SAVE_EVERY_REQUEST
SESSION_COOKIE_AGE = 60 * 60 * 24 * 365 * 10  # 10 ans (315360000 secondes)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Utiliser une variable d'environnement en production
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-5%&6bpaizqq8n)h7%7i7t&1dci^n+-entc_cy%_w4-aabu57o9')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG est False en production, True en développement
# Par défaut, True en développement local
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# Hosts autorisés
ALLOWED_HOSTS = [
    'aria-edu.com',
    'www.aria-edu.com',
    '157.173.102.180',
    'localhost',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # Django CORS Headers
    'django_countries',  # Django Countries pour la gestion des pays
    'school_admin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware (doit être avant CommonMiddleware)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'school_admin.middleware.UserTypeMiddleware',  # Doit être AVANT AuthenticationMiddleware
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'school_admin.middleware.AuthenticationMiddleware',  # Notre middleware d'authentification personnalisé
    'school_admin.middleware.SessionActiveMiddleware',  # Middleware pour la gestion des sessions actives
]

ROOT_URLCONF = 'school.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'school_admin' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'school_admin.context_processors.notifications_enseignant',
                'school_admin.context_processors.notifications_parent',
                'school_admin.context_processors.notifications_eleve',
                'school_admin.context_processors.periode_active',
            ],
        },
    },
]

WSGI_APPLICATION = 'school.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'goo_school'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'Ludvanne'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'client_encoding': 'UTF8',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True

# Configuration de l'encodage UTF-8
DEFAULT_CHARSET = 'utf-8'
FILE_CHARSET = 'utf-8'

# Configuration de l'encodage pour les templates
TEMPLATES[0]['OPTIONS']['context_processors'].extend([
    'django.template.context_processors.i18n',
])

# Configuration de l'encodage pour les formulaires
FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# STATIC_URL est déjà défini plus haut (ligne 22)

# Configuration pour la collecte des fichiers statiques en production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration du modèle d'utilisateur personnalisé
AUTH_USER_MODEL = 'school_admin.CompteUser'

# Configuration des backends d'authentification
AUTHENTICATION_BACKENDS = [
    'school_admin.authentication_backends.MultiUserBackend',
    'django.contrib.auth.backends.ModelBackend',  # Garder le backend par défaut en fallback
]

# Configuration des fichiers média
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuration du logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'] if not DEBUG else ['console'],
        'level': 'INFO' if not DEBUG else 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': 'INFO' if not DEBUG else 'WARNING',  # WARNING au lieu de DEBUG pour réduire les logs
            'propagate': False,
        },
        # Filtrer les messages DEBUG du système d'autoreload de Django
        'django.utils.autoreload': {
            'handlers': [],
            'level': 'WARNING',  # Ignorer tous les messages DEBUG d'autoreload
            'propagate': False,
        },
        'school_admin': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': 'INFO' if not DEBUG else 'DEBUG',
            'propagate': False,
        },
    },
}

# ============================================
# Configuration Wasender (WhatsApp OTP)
# ============================================
WASENDER_API_BASE_URL = os.getenv(
    "WASENDER_API_BASE_URL",
    "https://wasenderapi.com/api",
)
WASENDER_API_TOKEN = os.getenv(
    "WASENDER_API_TOKEN",
    "ec608d8488fcc95bb57fc9c43af6e0689e58599758ef2b1ac6cd8327bd540fc1",
)
WASENDER_DEFAULT_SESSION_ID = os.getenv("WASENDER_DEFAULT_SESSION_ID", "31658")

# ============================================
# Configuration de sécurité pour la production
# ============================================
# Configuration pour les proxies (Nginx)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookies sécurisés en HTTPS
SESSION_COOKIE_SECURE = not DEBUG  # True en production (HTTPS)
CSRF_COOKIE_SECURE = not DEBUG    # True en production (HTTPS)

# Headers de sécurité
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# HSTS (HTTP Strict Transport Security) - seulement en HTTPS
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 an
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ============================================
# Configuration CORS (Cross-Origin Resource Sharing)
# ============================================
# Désactiver CORS_ORIGIN_WHITELIST (déprécié)
CORS_ORIGIN_WHITELIST = []


# Utiliser CORS_ALLOWED_ORIGINS (nouvelle méthode)
CORS_ALLOWED_ORIGINS = [
    "https://aria-edu.com",
    "https://www.aria-edu.com",
    "http://157.173.102.180",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Autoriser les credentials (cookies, headers d'authentification)
CORS_ALLOW_CREDENTIALS = True

# Headers autorisés
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ============================================
# Configuration Email (SMTP)
# ============================================
EMAIL_BACKEND = 'school_admin.email_backends.CustomSMTPEmailBackend'
EMAIL_HOST = 'mail.aria-edu.com'
EMAIL_PORT = 587
EMAIL_USE_SSL = False
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'service@aria-edu.com'
EMAIL_HOST_PASSWORD = 'Ludvanne12@gmail.com'
DEFAULT_FROM_EMAIL = 'Aria - Plateforme de gestion scolaire <service@aria-edu.com>'
SERVER_EMAIL = 'service@aria-edu.com'